<main role="main">

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="/" class="homepage-link" title="Back to the frontpage">Home</a>
                </li>

                <li class="current">
                    <a href="#">Your Shopping Cart</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End Breadcrumbs -->


    <div class="row">
        <div class="row">
            <div class="small-12 medium-12 large-12 columns">
                <div class="cart">

                    <form id="form-cart" action="/cart" method="post">
                        <h1 class="h2">Shopping Cart</h1>
                        <div class="cart-content">



                            <div class="cart-item row">
                                <div class="small-12 large-6 columns">
                                    <div class="row">
                                        <div class="small-4 columns">
                                            <a href="/products/jabra-revo-wireless-bluetooth-stereo-headphones">
                                                <img src="//cdn.shopify.com/s/files/1/0750/3913/products/4_9fe2a9e8-3c8f-49cf-9896-71d95298f2b3_medium.jpeg?v=1421825322" alt="Jabra REVO Wireless Bluetooth Stereo Headphones - X / Red">
                                            </a>
                                        </div>
                                        <div class="small-8 columns">
                                            <h3 class="product-name">
                                                <a href="/products/jabra-revo-wireless-bluetooth-stereo-headphones">
                                                    Jabra REVO Wireless Bluetooth Stereo Headphones
                                                </a>
                                            </h3>

                                            <p class="">X / Red</p>


                                            <h5 class="brand">Apple, Shopify</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="small-12 large-6 columns">
                                    <div class="row">
                                        <div class="small-6 large-6 columns">


                                            <div class="js-qty">
                                                <button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="" data-qty="0">−</button>
                                                <input type="text" class="js-qty__num" value="1" min="1" data-id="" aria-label="quantity" pattern="[0-9]*" name="updates[]" id="updates_1114661080">
                                                <button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="" data-qty="11">+</button>
                                            </div>


                                        </div>
                                        <div class="small-4 large-4 columns text-right">
                                            <span class="price"><span class="money" data-currency-usd="$149.99">$149.99</span></span>
                                        </div>
                                        <div class="small-2 large-2 columns text-right">
                                            <a class="btn-remove" href="/cart/change?line=1&amp;quantity=0"><i class="fa fa-trash-o"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cart-item row">
                                <div class="small-12 large-6 columns">
                                    <div class="row">
                                        <div class="small-4 columns">
                                            <a href="/products/jabra-revo-wireless-bluetooth-stereo-headphones">
                                                <img src="//cdn.shopify.com/s/files/1/0750/3913/products/4_9fe2a9e8-3c8f-49cf-9896-71d95298f2b3_medium.jpeg?v=1421825322" alt="Jabra REVO Wireless Bluetooth Stereo Headphones - X / Red">
                                            </a>
                                        </div>
                                        <div class="small-8 columns">
                                            <h3 class="product-name">
                                                <a href="/products/jabra-revo-wireless-bluetooth-stereo-headphones">
                                                    Jabra REVO Wireless Bluetooth Stereo Headphones
                                                </a>
                                            </h3>

                                            <p class="">X / Red</p>


                                            <h5 class="brand">Apple, Shopify</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="small-12 large-6 columns">
                                    <div class="row">
                                        <div class="small-6 large-6 columns">


                                            <div class="js-qty">
                                                <button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="" data-qty="0">−</button>
                                                <input type="text" class="js-qty__num" value="1" min="1" data-id="" aria-label="quantity" pattern="[0-9]*" name="updates[]" id="updates_1114661080">
                                                <button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="" data-qty="11">+</button>
                                            </div>


                                        </div>
                                        <div class="small-4 large-4 columns text-right">
                                            <span class="price"><span class="money" data-currency-usd="$149.99">$149.99</span></span>
                                        </div>
                                        <div class="small-2 large-2 columns text-right">
                                            <a class="btn-remove" href="/cart/change?line=1&amp;quantity=0"><i class="fa fa-trash-o"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cart-function text-right">
                                <div class="cart-subtotal">Subtotal <span class="money" data-currency-usd="$149.99">$149.99</span></div>



                                <div class="function-buttons">
                                    <a class="button" href="/collections/boys" title="">Continue shopping</a>
                                    <input class="button btn-update" type="submit" name="update" value="Update Cart">
                                    <input class="button btn-checkout" type="submit" name="checkout" value="Check Out">
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</main>