<main role="main">

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="/trang-chu" class="homepage-link" title="Quay lại trang chủ">Trang chủ</a>
                </li>

                <li class="current">
                    <a href="#">Giỏ hàng của bạn</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End Breadcrumbs -->


    <div class="row">
        <div class="row">
            <div class="small-12 medium-12 large-12 columns">
                <div class="cart">

                    <form id="form-cart" action="/thong-tin-khach-hang" method="post">
                        <div class="cart-content">



                            <?php foreach ($showCart as $product): ?>
                                <div class="cart-item row">
                                    <div class="small-12 large-6 columns">
                                        <div class="row">
                                            <div class="small-4 columns">
                                                <a href="/san-pham/chi-tiet-san-pham/<?=$product->id?>">
                                                    <img src="/public/uploads/product/<?=$product->image?>" alt="<?=$product->name?>">
                                                </a>
                                            </div>
                                            <div class="small-8 columns">
                                                <h3 class="product-name">
                                                    <a href="/san-pham/chi-tiet-san-pham/<?=$product->id?>">
                                                        <?=$product->name?>
                                                    </a>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="small-12 large-6 columns">
                                        <div class="row product-detail">
                                            <div class="small-6 large-6 columns">


                                                <div class="js-qty" data-id="<?=$product->id?>">
                                                    <button type="button" class="js-qty__adjust js-qty__adjust--minus"  data-qty="0">−</button>
                                                    <input type="number" data-id="<?=$product->id?>" id="js-qty__num_cart" class="js-qty__num" value="<?=$product->quatity?>" min="1" max="10" name="updates[]">
                                                    <button type="button" class="js-qty__adjust js-qty__adjust--plus" data-qty="10">+</button>
                                                </div>


                                            </div>
                                            <div class="small-4 large-4 columns text-right">
                                                <span class="price"><span class="money" id="money_<?=$product->id?>" data-currency-usd="$149.99"><?=number_format($product->total ,0  , 0 , '.') ?> VND</span></span>
                                            </div>
                                            <div class="small-2 large-2 columns text-right">
                                                <a class="btn-remove" id="btn_remove_index" data-id="<?=$product->id?>" href="#"><i class="fa fa-trash-o"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>

                            <div class="cart-function text-right">
                                <div class="cart-subtotal">Tổng : <span class="money"><?= $this->session->get('totalCart')?></span></div>



                                <div class="function-buttons">
                                    <a id="nextOrder" class="button" href="/san-pham/tat-ca-san-pham" title="">Tiếp tục mua hàng</a>
<!--                                    <input class="button btn-update" type="submit" name="update" value="Update Cart">-->
                                    <input class="button btn-checkout" type="submit" name="checkout" value="Thanh toán">
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</main>