<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
            <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
            <div class="widget-box">
                <div class="widget-content nopadding" style="margin-bottom: -2%;">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/purchase_invoices/index",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "id" => "search_purchase_invoices"
                        ]
                    );
                    ?>
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Producer :</label>
                        <div class="controls">
                            <select name="province_id" id="province_id" style="border-radius: 4px">
                                <option value="">Choose..</option>
                                <?php foreach ($producers as $producer): ?>
                                    <option value="<?php echo $producer->id ?>"><?php echo $producer->company_name ?></option>
                                <?php endforeach; ?>
                            </select>

                        </div>
                    </div>
                    <div class="hidden">
                        <label class="control-label"></label>
                        <div class="controls">
                            <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,'style' => 'border-radius: 4px',  "id" => "submit-form"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                    <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                        <label class="control-label"></label>
                        <div class="controls" style="float: right; margin-top: -5%;">
                            <?php echo $this->tag->linkTo(["backend/purchase_invoices/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                            <button form="search_purchase_invoices" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="panel-body">
    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/purchase_invoices/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Invoices</button>']); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Province</th>
                <th style="background-color: #0288d1;color: #ffffff;">Name Seller</th>
                <th style="background-color: #0288d1;color: #ffffff;">Total</th>
                <th style="background-color: #0288d1;color: #ffffff;">Comment</th>
                <th style="background-color: #0288d1;color: #ffffff;">Action</th>
            </tr>
            <?php foreach ($page->items as $purchase_invoices): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/purchase_invoices/edit/" . $purchase_invoices->id, $purchase_invoices->id ]); ?></td>
                    <td><?php echo $purchase_invoices->company_name?></td>
                    <td><?php echo $purchase_invoices->name_seller ?></td>
                    <td><?php echo number_format($purchase_invoices->total ,0  , 0 , '.') ?></td>
                    <td><?php echo $purchase_invoices->comment ?></td>
                    <td><?php echo $this->tag->linkTo(["backend/purchase_invoices_detail/index/" . $purchase_invoices->id, "Các sản phẩm" , "class" => "btn btn-mini"  ]); ?>
                        <?php echo $this->tag->linkTo(["backend/purchase_invoices_detail/new/" . $purchase_invoices->id, "Thêm" , "class" => "btn btn-mini"  ]); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
