<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/product_detail/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'product_detail_edit'
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">

                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Product Name :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["product_name", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldProductName"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Shell Material :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["shell_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellMaterial"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Wire Material :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["wire_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWireMaterial"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Guarantee :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["guarantee", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGuarantee"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Glasses :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["glasses", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGlasses"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Shell Diameter :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["shell_diameter", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellDiameter"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Shell Thickness :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["shell_thickness", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellThickness"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Water Resistant :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["water_resistant", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWaterResistant"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Is Electronic :</label>
                        <div class="controls">

                            <?php if ($isElectronic){ ?>
                                <?php echo $this->tag->checkField (["is_electronic" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldIsElectronic"]) ?>
                            <?php }else{ ?>
                                <?php echo $this->tag->checkField (["is_electronic", "size" => 30, "class" => "form-control", "id" => "fieldIsElectronic"]) ?>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Motor :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["motor", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldMotor"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Comment :</label>
                        <div class="controls">
                            <?php echo $this->tag->textArea(["comment", "cols" => 30, "rows" => 4, "class" => "form-control",'style' => 'border-radius: 4px;width: 90%;', "id" => "fieldComment"]) ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="product_detail_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/product_detail/index", '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                        <?php echo $this->tag->linkTo(["backend/product_detail/delete/" . $id, '<button class="btn btn-danger icon-remove "><span class="glyphicon glyphicon-remove-circle"></span> Delete</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
