<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search product_detail
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["backend/product_detail/new", "Create product_detail"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "backend/product_detail/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductName" class="col-sm-2 control-label">Product Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_name", "size" => 30, "class" => "form-control", "id" => "fieldProductName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShellMaterial" class="col-sm-2 control-label">Shell Of Material</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shell_material", "size" => 30, "class" => "form-control", "id" => "fieldShellMaterial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWireMaterial" class="col-sm-2 control-label">Wire Of Material</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["wire_material", "size" => 30, "class" => "form-control", "id" => "fieldWireMaterial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGuarantee" class="col-sm-2 control-label">Guarantee</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["guarantee", "size" => 30, "class" => "form-control", "id" => "fieldGuarantee"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGlasses" class="col-sm-2 control-label">Glasses</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["glasses", "size" => 30, "class" => "form-control", "id" => "fieldGlasses"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShellDiameter" class="col-sm-2 control-label">Shell Of Diameter</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shell_diameter", "size" => 30, "class" => "form-control", "id" => "fieldShellDiameter"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldShellThickness" class="col-sm-2 control-label">Shell Of Thickness</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["shell_thickness", "size" => 30, "class" => "form-control", "id" => "fieldShellThickness"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWaterResistant" class="col-sm-2 control-label">Water Of Resistant</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["water_resistant", "size" => 30, "class" => "form-control", "id" => "fieldWaterResistant"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIsElectronic" class="col-sm-2 control-label">Is Of Electronic</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["is_electronic", "type" => "number", "class" => "form-control", "id" => "fieldIsElectronic"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMotor" class="col-sm-2 control-label">Motor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["motor", "size" => 30, "class" => "form-control", "id" => "fieldMotor"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldComment" class="col-sm-2 control-label">Comment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["comment", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldComment"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
