<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>


<div class="panel-body">
    <div class="row-fluid" style="margin-left: 10%">
        <div class="span9">
            <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
                <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
                <div class="widget-box">
                    <div class="widget-content nopadding" style="margin-bottom: -2%;">
                        <?php
                        echo $this->tag->form(
                            [
                                "backend/product_detail/index",
                                "autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id" => "search_product_detail"
                            ]
                        );
                        ?>

                        <div class="control-group">
                            <label class="control-label">Id :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Product Name :</label>
                            <div class="controls">
                                <select name="product_name" id="product_name" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($page->items as $product_detail): ?>
                                        <option value="<?php echo $product_detail->product_name ?>"><?php echo $product_detail->product_name ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Material :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellMaterial"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Wire Material :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["wire_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWireMaterial"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Guarantee :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["guarantee", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGuarantee"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Glasses :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["glasses", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGlasses"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Diameter :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_diameter", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellDiameter"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Thickness :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_thickness", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellThickness"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Water Resistant :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["water_resistant", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWaterResistant"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Type :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldType"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Kind of clock :</label>
                            <div class="controls">
                                <select name="is_electronic" id="is_electronic" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <option value="0">Đồng hồ cơ</option>
                                    <option value="1">Đồng hồ điện tử</option>
                                </select>
                            </div>
                        </div>

                        <div class="hidden">
                            <label class="control-label"></label>
                            <div class="controls">
                                <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,  "id" => "submit-form"]) ?>
                            </div>
                        </div>
                        <?php echo $this->tag->endForm(); ?>
                        <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                            <label class="control-label"></label>
                            <div class="controls" style="float: right; margin-top: -5%;">
                                <?php echo $this->tag->linkTo(["backend/product_detail/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                                <button form="search_product_detail" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/product_detail/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Product Detail</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Product Name</th>
                <th style="background-color: #0288d1;color: #ffffff;">Shell Material</th>
                <th style="background-color: #0288d1;color: #ffffff;">Wire Material</th>
                <th style="background-color: #0288d1;color: #ffffff;">Guarantee</th>
                <th style="background-color: #0288d1;color: #ffffff;">Glasses</th>
                <th style="background-color: #0288d1;color: #ffffff;">Shell Diameter</th>
                <th style="background-color: #0288d1;color: #ffffff;">Shell Thickness</th>
                <th style="background-color: #0288d1;color: #ffffff;">Water Resistant</th>
                <th style="background-color: #0288d1;color: #ffffff;">Is Electronic</th>
                <th style="background-color: #0288d1;color: #ffffff;">Motor</th>
                <th style="background-color: #0288d1;color: #ffffff;">Comment</th>

            </tr>
            <?php foreach ($page->items as $product_detail): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/product_detail/edit/" . $product_detail->id, $product_detail->id]); ?></td>
                    <td><?php echo $product_detail->product_name ?></td>
                    <td><?php echo $product_detail->shell_material ?></td>
                    <td><?php echo $product_detail->wire_material ?></td>
                    <td><?php echo $product_detail->guarantee ?></td>
                    <td><?php echo $product_detail->glasses ?></td>
                    <td><?php echo $product_detail->shell_diameter ?></td>
                    <td><?php echo $product_detail->shell_thickness ?></td>
                    <td><?php echo $product_detail->water_resistant ?></td>
                    <?php if ($product_detail->is_electronic){ ?>
                        <td><?php echo $this->tag->checkField ([ "onclick" => "return false;" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldIsElectronic"]) ?></td>
                    <?php }else{ ?>
                        <td><?php echo $this->tag->checkField (["onclick" => "return false;" , "size" => 30, "class" => "form-control", "id" => "fieldIsElectronic"]) ?></td>
                    <?php } ?>
                    <td><?php echo $product_detail->motor ?></td>
                    <td><?php echo $product_detail->comment ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
