<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row" style="margin-left: 2%;">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/product_detail/index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thêm mới</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <div class="form-horizontal">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/product_detail/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Product Name :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["product_name", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldProductName"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Material :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellMaterial"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Wire Material :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["wire_material", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWireMaterial"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Guarantee :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["guarantee", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGuarantee"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Glasses :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["glasses", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldGlasses"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Diameter :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_diameter", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellDiameter"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Shell Thickness :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["shell_thickness", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldShellThickness"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Water Resistant :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["water_resistant", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldWaterResistant"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Is Electronic :</label>
                            <div class="controls">
                                <?php echo $this->tag->checkField (["is_electronic" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldIsElectronic"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Motor :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["motor", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldMotor"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Comment :</label>
                            <div class="controls">
                                <?php echo $this->tag->textArea(["comment", "cols" => 30, "rows" => 4, "class" => "form-control",'style' => 'border-radius: 4px;width: 90%;', "id" => "fieldComment"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="span12">
                                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default" ,  "style" => "float: right ;margin: 1%;"]) ?>
                            </div>
                        </div>

                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>
        </div>
    </div>




