<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/sales_invoice/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'invoice_edit',
                        "enctype" => "multipart/form-data"
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">

                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id" , 'readonly' => 'true' , "size" => 30, "class" => "form-control"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" style="margin-top: -5px">Province :</label>
                        <div class="controls">
                            <select name="province_id" id="province_id_backend" style="border-radius: 4px">
                                <?php foreach ($province as $provinces): ?>
                                    <?php if ($provinces->provinceid == $province_id){ ?>
                                        <option value="<?php echo $provinces->provinceid ?>" selected><?php echo $provinces->name ?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $provinces->provinceid ?>"><?php echo $provinces->name ?></option>
                                    <?php } ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">District :</label>
                        <div class="controls">
                            <select name="district_id" id="district_id_backend" style="border-radius: 4px">
                                <?php foreach ($district as $districts): ?>
                                    <?php if ($districts->districtid == $district_id){ ?>
                                        <option value="<?php echo $districts->districtid ?>" selected><?php echo $districts->name ?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $districts->districtid ?>"><?php echo $districts->name ?></option>
                                    <?php } ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Phone :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Email :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Name :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["fullname", "size" => 30, "class" => "form-control", "id" => "fieldFullname"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Address detail :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Status :</label>
                        <div class="controls">
                            <select name="status" id="status" style="border-radius: 4px">
                                <option value="NEW" <?= $status == 'NEW' ? 'selected' : null ?> >NEW</option>
                                <option value="PENDING" <?= $status == 'PENDING' ? 'selected' : null ?> >PENDING</option>
                                <option value="FINISH" <?= $status == 'FINISH' ? 'selected' : null ?> >FINISH</option>
                            </select>
                        </div>
                    </div>

                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="invoice_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/sales_invoice/index", '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


