<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
            <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
            <div class="widget-box">
                <div class="widget-content nopadding" style="margin-bottom: -2%;">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/sales_invoice/index",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "id" => "search_invoice"
                        ]
                    );
                    ?>
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Province :</label>
                        <div class="controls">
                            <select name="province_id" id="province_id" style="border-radius: 4px">
                                <option value="">Choose..</option>
                                <?php foreach ($provinces as $province): ?>
                                    <option value="<?php echo $province->provinceid ?>"><?php echo $province->name ?></option>
                                <?php endforeach; ?>
                            </select>

                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Phone  :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", 'style' => 'border-radius: 4px', "id" => "fieldPhone"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Email :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", 'style' => 'border-radius: 4px', "id" => "fieldEmail"]) ?>
                        </div>
                    </div>
                    <div class="hidden">
                        <label class="control-label"></label>
                        <div class="controls">
                            <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,'style' => 'border-radius: 4px',  "id" => "submit-form"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                    <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                        <label class="control-label"></label>
                        <div class="controls" style="float: right; margin-top: -5%;">
                            <?php echo $this->tag->linkTo(["backend/sales_invoice/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                            <button form="search_invoice" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="panel-body">
    
    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Province</th>
                <th style="background-color: #0288d1;color: #ffffff;">District</th>
                <th style="background-color: #0288d1;color: #ffffff;">Pay Method</th>
                <th style="background-color: #0288d1;color: #ffffff;">Phone</th>
                <th style="background-color: #0288d1;color: #ffffff;">Email</th>
                <th style="background-color: #0288d1;color: #ffffff;">Fullname</th>
                <th style="background-color: #0288d1;color: #ffffff;">Address</th>
                <th style="background-color: #0288d1;color: #ffffff;">Shipping</th>
                <th style="background-color: #0288d1;color: #ffffff;">Total</th>
                <th style="background-color: #0288d1;color: #ffffff;">Status</th>
                <th style="background-color: #0288d1;color: #ffffff;">Action</th>

            </tr>
            <?php foreach ($page->items as $billInvoice): ?>
                <tr>

                    <td><?php echo $this->tag->linkTo(["backend/sales_invoice/edit/" . $billInvoice->id, $billInvoice->id ]); ?></td>
                    <td><?php echo $billInvoice->province?></td>
                    <td><?php echo $billInvoice->district ?></td>
                    <td><?php echo $billInvoice->pay_method_id ?></td>
                    <td><?php echo $billInvoice->phone ?></td>
                    <td><?php echo $billInvoice->email ?></td>
                    <td><?php echo $billInvoice->fullname ?></td>
                    <td><?php echo $billInvoice->address ?></td>
                    <td><?php echo number_format($billInvoice->shipping ,0  , 0 , '.')  ?></td>
                    <td><?php echo number_format($billInvoice->total ,0  , 0 , '.')  ?></td>
                    <td><?php echo $billInvoice->status ?></td>
                    <td><?php echo $this->tag->linkTo(["backend/sales_invoice_detail/index/" . $billInvoice->id, "Các sản phẩm" , "class" => "btn btn-mini"  ]); ?></td>
                  </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
