<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["sales_invoice/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["sales_invoice/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Member</th>
            <th>Province</th>
            <th>District</th>
            <th>Pay Of Method</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Fullname</th>
            <th>Address</th>
            <th>Shipping</th>
            <th>Total</th>
            <th>Status</th>
            <th>Created</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $sales_invoice): ?>
            <tr>
                <td><?php echo $sales_invoice->id ?></td>
            <td><?php echo $sales_invoice->member_id ?></td>
            <td><?php echo $sales_invoice->province_id ?></td>
            <td><?php echo $sales_invoice->district_id ?></td>
            <td><?php echo $sales_invoice->pay_method_id ?></td>
            <td><?php echo $sales_invoice->phone ?></td>
            <td><?php echo $sales_invoice->email ?></td>
            <td><?php echo $sales_invoice->fullname ?></td>
            <td><?php echo $sales_invoice->address ?></td>
            <td><?php echo $sales_invoice->shipping ?></td>
            <td><?php echo $sales_invoice->total ?></td>
            <td><?php echo $sales_invoice->status ?></td>
            <td><?php echo $sales_invoice->created_at ?></td>

                <td><?php echo $this->tag->linkTo(["sales_invoice/edit/" . $sales_invoice->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["sales_invoice/delete/" . $sales_invoice->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("sales_invoice/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
