<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<?php echo $this->getContent(); ?>

<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/users/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'users_edit'
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">

                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id" , 'readonly' => 'true' , "size" => 30, "class" => "form-control"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Username :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" style="margin-top: -5px">Password :</label>
                        <div class="controls">
                            <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Active :</label>
                        <div class="controls">
                            <?php if ($active){ ?>
                                <?php echo $this->tag->checkField (["active" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldActive"]) ?>
                            <?php }else{ ?>
                                <?php echo $this->tag->checkField (["active", "size" => 30, "class" => "form-control", "id" => "fieldActive"]) ?>
                            <?php } ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Is Admin :</label>
                        <div class="controls">
                            <?php if ($is_admin){ ?>
                                <?php echo $this->tag->checkField (["is_admin" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldIsAdmin"]) ?>
                            <?php }else{ ?>
                                <?php echo $this->tag->checkField (["is_admin"  , "size" => 30, "class" => "form-control", "id" => "fieldIsAdmin"]) ?>
                            <?php } ?>
                        </div>
                    </div>

                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="users_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/users/index", '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                        <?php echo $this->tag->linkTo(["backend/users/delete/" . $id, '<button class="btn btn-danger icon-remove "><span class="glyphicon glyphicon-remove-circle"></span> Delete</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



