<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>





<div class="panel-body">

    <div class="row-fluid" style="margin-left: 10%">
        <div class="span9">
            <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%;">
                <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
                <div class="widget-box">
                    <div class="widget-content nopadding" style="margin-bottom: -2%;">
                        <?php
                        echo $this->tag->form(
                            [
                                "backend/users/index",
                                "autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id" => "search_users"
                            ]
                        );
                        ?>
                        <div class="control-group">
                            <label class="control-label">Id :</label>
                            <div class="controls ">
                                <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control ", 'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Username :</label>
                            <div class="controls boder_input">
                                <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control ",'style' => 'border-radius: 4px', "id" => "fieldUsername"]) ?>
                            </div>
                        </div>
                        <div class="hidden">
                            <label class="control-label"></label>
                            <div class="controls">
                                <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,  "id" => "submit-form"]) ?>
                            </div>
                        </div>
                        <?php echo $this->tag->endForm(); ?>
                        <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                            <label class="control-label"></label>
                            <div class="controls" style="float: right; margin-top: -5%;">
                                <button form="search_users" class="btn btn-info icon-search"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/users/new", ' <button class="btn btn-success"  style="margin-bottom: 5%;"><span class="glyphicon glyphicon-user"></span> Add New Producer</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Username</th>
                <th style="background-color: #0288d1;color: #ffffff;">Active</th>
                <th style="background-color: #0288d1;color: #ffffff;">Is Admin</th>
            </tr>

            <?php foreach ($page->items as $user): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/users/edit/" . $user->id, $user->id ]); ?></td>
                    <td><?php echo $user->username ?></td>
                    <?php if ($user->active){ ?>
                        <td><?php echo $this->tag->checkField ([ "onclick" => "return false;" , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldActive"]) ?></td>
                    <?php }else{ ?>
                        <td><?php echo $this->tag->checkField (["onclick" => "return false;" , "size" => 30, "class" => "form-control", "id" => "fieldActive"]) ?></td>
                    <?php } ?>
                    <?php if ($user->is_admin){ ?>
                        <td><?php echo $this->tag->checkField ([ "onclick" => "return false;"  , "checked" => "checked" , "size" => 30, "class" => "form-control", "id" => "fieldIsAdmin"]) ?></td>
                    <?php }else{ ?>
                        <td><?php echo $this->tag->checkField ([ "onclick" => "return false;"  , "size" => 30, "class" => "form-control", "id" => "fieldIsAdmin"]) ?></td>
                    <?php } ?>

                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>