<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<div class="row" style="margin-left: 2%;">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/users/index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thêm mới</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <div class="form-horizontal">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/users/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Username :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
                        </div>
                    </div>

                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Password :</label>
                            <div class="controls">
                                <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
                        </div>
                    </div>

                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Active :</label>
                            <div class="controls">
                                <?php echo $this->tag->checkField ([ "active", "size" => 30, "class" => "form-control", "id" => "fieldActive"]) ?>
                        </div>
                    </div>

                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Is Admin :</label>
                            <div class="controls">
                                <?php echo $this->tag->checkField (["is_admin", "size" => 30, "class" => "form-control", "id" => "fieldIsAdmin"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="span12">
                            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default" ,  "style" => "float: right ;margin: 1%;"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

