<main role="main">

    <?php $this->partial('index/slideshow') ?>


    <?php $this->partial('index/horizontalanimate') ?>

    <script>
        $(document).ready(function() {
            $("#categories-scroll").owlCarousel({
                items : 4,
                autoPlay : true,
                stopOnHover : true,
                pagination : false
            });
        })
    </script>

    <?php $this->partial('index/bannershow') ?>




    <?php $this->partial("Index/newproduct") ?>






    <!--div class="large-12 columns shopify-welcome-message">
        <div class="panel">
            <p>Write a few sentences to tell people about your store (the kind of products you sell, your mission, etc). You can also add images and videos to help tell your story and generate more interest in your shop.</p>
    <p>To edit the content on this page, go to the <a href="/admin/pages">Pages</a> section of your Shopify admin.</p>
        </div>
          <br />
    </div-->






    <div id="brand">
        <div class="box-content">
            <div class="row">
                <div id="brand-scroll">




                    <div class="brand-box">
                        <a href="collections/girls.html" title="Lighting">
                            <img src="/public/img/brand1e0a9.png?4621688722820174607" alt="Lighting" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Nextstore">
                            <img src="/public/img/brand2e0a9.png?4621688722820174607" alt="Nextstore" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Bigshop">
                            <img src="/public/img/brand3e0a9.png?4621688722820174607" alt="Bigshop" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Station">
                            <img src="/public/img/brand4e0a9.png?4621688722820174607" alt="Station" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="maxxshop">
                            <img src="/public/img/brand5e0a9.png?4621688722820174607" alt="maxxshop" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Gentshop">
                            <img src="/public/img/brand6e0a9.png?4621688722820174607" alt="Gentshop" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Nike">
                            <img src="/public/img/brand7e0a9.png?4621688722820174607" alt="Nike" />
                        </a>
                    </div>






                    <div class="brand-box">
                        <a href="collections/girls.html" title="Doll">
                            <img src="/public/img/brand8e0a9.png?4621688722820174607" alt="Doll" />
                        </a>
                    </div>



                </div>
            </div>
        </div>

    </div>

    <script>
        $(document).ready(function() {
            $("#brand-scroll").owlCarousel({
                items : 6,
                autoPlay : true,
                stopOnHover : true,
                pagination : false
            });

        })

    </script>



</main>