
<nav class="tab-bar show-for-small">
    <section class="row text-center topbar-mobile">
        <div class="small-4 columns ">
            <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
        </div>
        <div class="small-4 columns ">
            <button data-dropdown="use" aria-controls="use" aria-expanded="false" class="no-btn"><i class="fa fa-user"></i></button>

            <ul id="use" class="f-dropdown mobile-links" data-dropdown-content aria-hidden="true" tabindex="-1">

                <li>
                    <?php if( $this->session->get('user_name')){?>
                        <a href="#" id="customer_login_link"><?php echo $this->session->get('user_name')?></a>
                    <?php }else{ ?>
                        <a href="/dang-nhap" id="customer_login_link">Đăng nhập</a>
                    <?php } ?>
                </li>
                <li>
                    <?php if( $this->session->get('user_name')){?>
                        <a href="/account/logout" id="customer_login_link">Đăng xuất</a>
                    <?php }else{ ?>
                        <a href="/dang-ky" id="customer_register_link">Đăng ký</a>
                    <?php } ?>
                </li>

            </ul>

        </div>
        <div class="small-4 columns ">
            <a class="right-off-canvas-toggle menu-icon" href="#"><i class="fa fa-shopping-cart"></i></a>
        </div>
    </section>
</nav>
<aside class="left-off-canvas-menu">
    <!--Top Menu -->

    <!-- This is where the main menu links render-->
    <ul class="mobile-menu">






        <li class="nav-item first ">
            <a href="/trang-chu" title="Home">Trang chủ</a>

        </li>

        <li class="nav-item has-dropdown">
            <a href="/san-pham/tat-ca-san-pham" title="Catalog">Danh mục</a>

            <ul class="dropdown">

                <li class=" first has-dropdown">
                    <a href="/san-pham/san-pham-nam" title="Men">Nam</a>

                </li>

                <li class=" ">
                    <a href="/san-pham/san-pham-nu" title="Women">Nữ</a>

                </li>

            </ul>

        </li>

        <li class="nav-item ">
            <a href="#" title="Blog">Blog</a>

        </li>

        <li class="nav-item last ">
            <a href="#" title="About Us">Về chúng tôi</a>

        </li>

    </ul>

    <!-- End Menu -->
</aside>
<aside class="right-off-canvas-menu">
    <div class="topcart">

        <div>
            <p class="empty">Your cart is currently empty!</p>
        </div>

    </div>
</aside>