<div class="latest-products box">

    <div class="box-title">
        <h3>Sản phẩm mới</h3>
        <span class="abs"><i class="fa fa-star"></i></span>
    </div>
    <div class="box-content">
        <div class="products-row row">
            <div id="latest-products" class="owl-control">
                <?php foreach ($newProduct as $product): ?>
                <div class="item">
                    <div class="product-image">
                        <div class="action">
                            <?php if ($product->quantity == 0){ ?>
                                <input type="button" data-id="<?= $product->id ?>" value="Tạm hết hàng" class="btn ct-btn" />
                            <?php }else{ ?>
                                <input id="btnQuickOder" type="button" data-id="<?= $product->id ?>" value="Thêm vào giỏ hàng" class="btn ct-btn" />
                            <?php } ?>
                            <div data-options="disable_for_touch:true" >
                                <a class="quick-view ct-btn" data-id="<?= $product->id ?>" id="btn_quick_view" href="#" data-reveal-id="sp<?= $product->id ?>" title="<?= $product->product_name ?>">
                                    Xem ngay
                                </a>
                            </div>
                            <div id="sp<?= $product->id ?>" class="reveal-modal expand" style="position:fixed;" data-reveal>
                                    <div class="row">
                                        <div class="large-6 columns">
                                            <script>
                                                $(document).ready(function(){
                                                    $('#zoom-<?= $product->description_id ?>').zoom();
                                                    $('#grab-<?= $product->description_id ?>').zoom({ on:'grab' });
                                                    $('#click-<?= $product->description_id ?>').zoom({ on:'click' });
                                                    $('#toggle-<?= $product->description_id ?>').zoom({ on:'toggle' });
                                                });
                                            </script>
                                            <div id="zoom-<?= $product->description_id ?>">
                                                <img src="/public/uploads/product/<?= $product->image ?>" alt="<?= $product->product_name ?>" />
                                            </div>
                                        </div>
                                        <div class="large-6 columns">
                                            <h1 itemprop="name"><?= $product->product_name ?></h1>
                                            <div class="review text-left">
                                                <span itemprop="name">MSP: <?= $product->description_id?></span>
                                                <span class="shopify-product-reviews-badge" data-id="<?= $product->id ?>"></span>
                                            </div>
<!--                                            <div id="product-description" class="rte" itemprop="description">-->
<!--                                                <p>The standard Lorem Ipsum passage, used since the 1500s"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...</p>-->
<!--                                            </div>-->
                                            <div id="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                                <meta itemprop="priceCurrency" content="USD" />

                                                <link itemprop="availability" href="http://schema.org/InStock" />

                                                <h5>
                                                    <?php if($product->discount){ ?>
                                                        <span class="price" itemprop="price"><span ><?= number_format((int)$product->sale_price - ((int)$product->discount/100 * (int)$product->sale_price) ,0  , 0 , '.')?> VND</span></span>
                                                        &nbsp;<s class="sale-price"><span class="money" ><?= number_format($product->sale_price ,0  , 0 , '.')?></span></s>
                                                    <?php }else{ ?>
                                                        <span class="price" itemprop="price"><span ><?= number_format($product->sale_price ,0  , 0 , '.')?> VND</span></span>
                                                    <?php } ?>
                                                </h5>
                                            </div>
                                            <div id="product-add">
                                                <div class="qty-adder qty-adder pull-left" data-id="<?= $product->id ?>">
                                                    <div class="quantity-number pull-left">
                                                        <a href="javascript:void(0)" title=""><span class="add-down add-action">-</span></a>
                                                        <input class="quantity_<?= $product->id ?>" id="quantity" type="text" name="quantity" size="2" value="1">
                                                        <a href="javascript:void(0)" title=""><span class="add-up add-action">+</span></a>
                                                    </div>
                                                </div>
                                                <?php if ($product->quantity == 0){ ?>
                                                    <input type="button" data-id="<?= $product->id ?>" value="Tạm hết hàng" class="btn ct-btn" />
                                                <?php }else{ ?>
                                                    <input class="button" type="button" data-id="<?= $product->id ?>" name="add" id="addShopcart" value="Thêm vào giỏ hàng">
                                                <?php } ?>
                                            </div>
                                            <!-- Sharing is caring -->

                                            <div class="large-12 columns">
                                                <br />
                                                <ul class="social-sharing inline-list">
                                                    <li>Share: </li>
                                                    <li><a target="_blank" href="https://twitter.com/intent/tweet?text=&amp;url=http%3A%2F%2Fap-best-store.myshopify.com&amp;via=rcinteriors"><i class="fi-social-twitter"></i></a></li>
                                                    <li><a target="_blank" href="http://www.facebook.com/sharer/sharer.php?u=http://ap-best-store.myshopify.com"><i class="fi-social-facebook"></i></a></li>
                                                    <li><a target="_blank" href="https://plus.google.com/share?url=http://ap-best-store.myshopify.com"><i class="fi-social-google-plus"></i></a></li>
                                                    <li><a target="_blank" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=http://ap-best-store.myshopify.com&amp;title=&amp;summary=&amp;source=http://ap-best-store.myshopify.com"><i class="fi-social-linkedin"></i></a></li>
                                                    <li><a target="_blank" href="http://pinterest.com/pin/create/button/?url=http://ap-best-store.myshopify.com&amp;description=&amp;media="><i class="fi-social-pinterest"></i></a></li>
                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                <a class="close-reveal-modal">&#215;</a>
                            </div>

                        </div>
                        <?php if($product->discount){ ?>
                            <span class="sale-tag"></span>
                        <?php } ?>
                        <img style="height: 250px" src="/public/uploads/product/<?= $product->image ?>" alt="<?= $product->product_name ?>" />
                    </div>
                    <div class="product-info">
                        <h3 class="product-name"><a href= "/san-pham/chi-tiet-san-pham/<?= $product->id ?>"><?= $product->product_name ?></a></h3>


                        <div class="review">
                            <span class="shopify-product-reviews-badge" data-id="<?= $product->id ?>"></span>
                        </div>

                        <span class="price">
                        <?php if($product->discount){ ?>
                            <del>
                            <span class="sale-price">
                                <span class="money" data-currency-usd="$40.00"><?= number_format($product->sale_price ,0  , 0 , '.')  ?></span>
                            </span>
                            </del>
                            <span ><?= number_format((int)$product->sale_price - ((int)$product->discount/100 * (int)$product->sale_price) ,0  , 0 , '.')?> VND</span>
                        <?php }else{ ?>
                            <span ><?= number_format($product->sale_price ,0  , 0 , '.')?> VND</span>
                        <?php } ?>

                    </span>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<script>
    jQuery(function($) {

        $(".qty-adder .add-action").click( function(){
            var id = $(this).closest('.qty-adder').data('id');
            console.log(id);
            if( $(this).hasClass('add-up') ) {
                var countInput  = $(this).parent().prev();
                var count = countInput.val();
                console.log(count);
                var  value = parseInt( count ) + 1;
                countInput.val(value );
            }else {
                var countInput  = $(this).parent().next();
                var count = countInput.val();
                console.log(count);
                if( parseInt(countInput.val())  > 1 ) {
                    countInput.val( count - 1 );
                }
            }
        });
    });
</script>
<script>
    $(document).ready(function() {
        $("#latest-products").owlCarousel({
            itemsCustom : [
                [0, 1],
                [450, 1],
                [600, 2],
                [700, 2],
                [1000, 4],
                [1200, 5],
                [1400, 5],
                [1600, 5]
            ],
            autoPlay : false,
            stopOnHover : false,
            lazyLoad : false,
            lazyFollow : true,
            lazyEffect : "fade",
            afterInit : function(el){
                el.trigger('owl.jumpTo',2)
            },
            pagination : false,
            // Navigation
            navigation : true,
            navigationText : ["prev","next"],
            rewindNav : true,
            scrollPerPage : false,
        });
    })
</script>


