<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
            <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
            <div class="widget-box">
                <div class="widget-content nopadding" style="margin-bottom: -2%;">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/member/index",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "id" => "search_member"
                        ]
                    );
                    ?>
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control" , 'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Name :</label>
                        <div class="controls">
                            <select name="fullname" id="fullname" style="border-radius: 4px">
                                <option value="">Choose..</option>
                            <?php foreach ($page->items as $member): ?>
                                <option value="<?php echo $member->fullname ?>"><?php echo $member->fullname ?></option>
                            <?php endforeach; ?>
                            </select>

                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Phone Number :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", 'style' => 'border-radius: 4px', "id" => "fieldPhoneNumber"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Email :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", 'style' => 'border-radius: 4px', "id" => "fieldEmail"]) ?>
                        </div>
                    </div>
                    <div class="hidden">
                        <label class="control-label"></label>
                        <div class="controls">
                            <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,'style' => 'border-radius: 4px',  "id" => "submit-form"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                    <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                        <label class="control-label"></label>
                        <div class="controls" style="float: right; margin-top: -5%;">
                            <?php echo $this->tag->linkTo(["backend/member/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                            <button form="search_member" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="panel-body">

    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/member/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Member</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Fullname</th>
                <th style="background-color: #0288d1;color: #ffffff;">Sex</th>
                <th style="background-color: #0288d1;color: #ffffff;">Phone Of Number</th>
                <th style="background-color: #0288d1;color: #ffffff;">Email</th>
                <th style="background-color: #0288d1;color: #ffffff;">Number Hits</th>
                <th style="background-color: #0288d1;color: #ffffff;">Address</th>
                <th style="background-color: #0288d1;color: #ffffff;">Avatar</th>

            </tr>
            <?php foreach ($page->items as $member): ?>
                <tr>

                    <td><?php echo $this->tag->linkTo(["backend/member/edit/" . $member->id, $member->id ]); ?></td>
                    <td><?php echo $member->fullname ?></td>
                    <td><?php echo $member->sex ? 'Nam' : 'Nữ' ?></td>
                    <td><?php echo $member->phone_number ?></td>
                    <td><?php echo $member->email ?></td>
                    <td><?php echo $member->number_hits ?></td>
                    <td><?php echo $member->address ?></td>
                    <td><?php echo $this->tag->image(['public/uploads/member/'.$member->avatar , "alt" => " alt member " , "style" => "width: 100px;height: 100px;" ]) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>