<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["member/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["member/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Fullname</th>
            <th>Sex</th>
            <th>Phone Of Number</th>
            <th>Email</th>
            <th>Password</th>
            <th>Number Of Hits</th>
            <th>Address</th>
            <th>Avatar</th>
            <th>Created</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $member): ?>
            <tr>
                <td><?php echo $member->id ?></td>
            <td><?php echo $member->fullname ?></td>
            <td><?php echo $member->sex ?></td>
            <td><?php echo $member->phone_number ?></td>
            <td><?php echo $member->email ?></td>
            <td><?php echo $member->password ?></td>
            <td><?php echo $member->number_hits ?></td>
            <td><?php echo $member->address ?></td>
            <td><?php echo $member->avatar ?></td>
            <td><?php echo $member->created_at ?></td>

                <td><?php echo $this->tag->linkTo(["member/edit/" . $member->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["member/delete/" . $member->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("member/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("member/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("member/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("member/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
