<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/product/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'product_edit'
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">

                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id" , 'readonly' => 'true' , "size" => 30, "class" => "form-control"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Producer Name :</label>
                        <div class="controls">
                            <select name="producer_id" id="producer_id" style="border-radius: 4px">
                                <?php foreach ($producer as $producers): ?>
                                    <?php if ($producers->id == $producer_id){ ?>
                                        <option value="<?php echo $producers->id ?>" selected><?php echo $producers->company_name ?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $producers->id ?>"><?php echo $producers->company_name ?></option>
                                    <?php } ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Description Id :</label>
                        <div class="controls">
                            <select name="description_id" id="description_id" style="border-radius: 4px">
                                <?php foreach ($product as $products): ?>
                                    <?php if ($products->description_id == $description_id){ ?>
                                        <option value="<?php echo $products->description_id ?>" selected><?php echo $products->description_id ?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $products->description_id ?>"><?php echo $products->description_id ?></option>
                                    <?php } ?>

                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Product name :</label>
                        <div class="controls">
                            <select name="product_detail_id" id="product_detail_id" style="border-radius: 4px">
                                <?php foreach ($productDetail as $product_detail): ?>
                                    <?php if ($product_detail->id == $product_detail_id){ ?>
                                        <option value="<?php echo $product_detail->id ?>"><?php echo $product_detail->product_name?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $product_detail->id ?>"><?php echo $product_detail->product_name?></option>
                                    <?php } ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Quantity :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["quantity" , "type" => "number" , "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldQuantity"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Import Price :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["import_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldImportPrice"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Sale Price :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["sale_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldSalePrice"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Discount :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["discount", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldDiscount"]) ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="product_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/product/index", '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                        <?php echo $this->tag->linkTo(["backend/product/delete/" . $id, '<button class="btn btn-danger icon-remove "><span class="glyphicon glyphicon-remove-circle"></span> Delete</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>