<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["product", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit product
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "product/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldProducerId" class="col-sm-2 control-label">Producer</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["producer_id", "type" => "number", "class" => "form-control", "id" => "fieldProducerId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescriptionId" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description_id", "type" => "number", "class" => "form-control", "id" => "fieldDescriptionId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductDetailId" class="col-sm-2 control-label">Product Of Detail</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_detail_id", "type" => "number", "class" => "form-control", "id" => "fieldProductDetailId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImportPrice" class="col-sm-2 control-label">Import Of Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["import_price", "size" => 30, "class" => "form-control", "id" => "fieldImportPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSalePrice" class="col-sm-2 control-label">Sale Of Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sale_price", "size" => 30, "class" => "form-control", "id" => "fieldSalePrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDiscount" class="col-sm-2 control-label">Discount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["discount", "size" => 30, "class" => "form-control", "id" => "fieldDiscount"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageId" class="col-sm-2 control-label">Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["image_id", "type" => "number", "class" => "form-control", "id" => "fieldImageId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldView" class="col-sm-2 control-label">View</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["view", "type" => "number", "class" => "form-control", "id" => "fieldView"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedAt" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created_at", "size" => 30, "class" => "form-control", "id" => "fieldCreatedAt"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
