<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<?php use Phalcon\Tag; ?>

<div class="panel-body">
    <div class="row-fluid" style="margin-left: 10%">
        <div class="span9">
            <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
                <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
                <div class="widget-box">
                    <div class="widget-content nopadding" style="margin-bottom: -2%;">
                        <?php
                        echo $this->tag->form(
                            [
                                "backend/product/index",
                                "autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id" => "search_product"
                            ]
                        );
                        ?>

                            <div class="control-group">
                                <label class="control-label">Id :</label>
                                <div class="controls">
                                    <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                                </div>
                            </div>
                        <div class="control-group">
                            <label class="control-label">Producer Name :</label>
                            <div class="controls">
                                <select name="producer_id" id="producer_id" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($producer as $producers): ?>
                                        <option value="<?php echo $producers->id ?>"><?php echo $producers->company_name ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Description Id :</label>
                            <div class="controls">
                                <select name="description_id" id="description_id" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($product as $products): ?>
                                        <option value="<?php echo $products->description_id ?>"><?php echo $products->description_id ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Product name :</label>
                            <div class="controls">
                                <select name="product_detail_id" id="product_detail_id" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($productDetail as $product_detail): ?>
                                        <option value="<?php echo $product_detail->id ?>"><?php echo $product_detail->product_name?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Quantity :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["quantity" , "type" => "number" , "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldQuantity"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Import Price :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["import_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldImportPrice"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Sale Price :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["sale_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldSalePrice"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Discount :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["discount", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldDiscount"]) ?>
                            </div>
                        </div>


                        <div class="hidden">
                                <label class="control-label"></label>
                                <div class="controls">
                                    <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,  "id" => "submit-form"]) ?>
                                </div>
                            </div>
                        <?php echo $this->tag->endForm(); ?>
                        <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                            <label class="control-label"></label>
                            <div class="controls" style="float: right; margin-top: -5%;">
                                <?php echo $this->tag->linkTo(["backend/product/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                                <button form="search_product" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/product/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Product</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Producer</th>
                <th style="background-color: #0288d1;color: #ffffff;">Description</th>
                <th style="background-color: #0288d1;color: #ffffff;">Product name</th>
                <th style="background-color: #0288d1;color: #ffffff;">Quantity</th>
                <th style="background-color: #0288d1;color: #ffffff;">Import Price</th>
                <th style="background-color: #0288d1;color: #ffffff;">Sale Price</th>
                <th style="background-color: #0288d1;color: #ffffff;">Discount(%)</th>
                <th style="background-color: #0288d1;color: #ffffff;">View</th>

            </tr>

            <?php foreach ($page->items as $product): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/product/edit/" . $product->id, $product->id]); ?></td>
                    <td><?php echo $product->company_name ?></td>
                    <td><?php echo $product->description_id ?></td>
                    <td><?php echo $product->product_name ?></td>
                    <td><?php echo $product->quantity ?></td>
                    <td><?php echo number_format($product->import_price ,0  , 0 , '.') ?></td>
                    <td><?php echo number_format($product->sale_price ,0  , 0 , '.') ?></td>
                    <td><?php echo $product->discount ?></td>
                    <td><?php echo $product->view ?></td>

                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>