<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row" style="margin-left: 2%;">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/product/index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thêm mới</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <div class="form-horizontal">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/product/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Producer Name :</label>
                            <div class="controls">
                                <select name="producer_id" id="producer_id" style="border-radius: 4px">
                                    <?php foreach ($producer as $producers): ?>
                                        <option value="<?php echo $producers->id ?>"><?php echo $producers->company_name ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Description Id :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["description_id" , "type" => "text" , "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldDescriptionId"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Product name :</label>
                            <div class="controls">
                                <select name="product_detail_id" id="product_detail_id" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($productDetail as $product_detail): ?>
                                        <option value="<?php echo $product_detail->id ?>"><?php echo $product_detail->product_name?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Quantity :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["quantity" , "type" => "number" , "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldQuantity"]) ?>
                            </div>
                        </div>
                         <div class="control-group">
                            <label class="control-label">Import Price :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["import_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldImportPrice"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Sale Price :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["sale_price", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldSalePrice"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Discount :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["discount", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldDiscount"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Type :</label>
                            <div class="controls">
                                <ul class="container_checkbox">
                                    <?php foreach ($productType as $product_type): ?>
                                        <li>
                                            <input type="checkbox" name="product_credentials[]" id="product_credentials_<? echo $product_type->id ?>" value="<? echo $product_type->id ?>">
                                            <label for="product_credentials_<? echo $product_type->id ?>"><? echo $product_type->name ?></label>
                                        </li>

                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="span12">
                                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default" ,  "style" => "float: right ;margin: 1%;"]) ?>
                            </div>
                        </div>

                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>
        </div>
    </div>




