
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/purchase_invoices_detail/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'purchase_invoices_detail_edit',
                        "enctype" => "multipart/form-data"
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">
                    <input style="visibility: hidden;display: none" name="purchase_invoices_id" id="fieldPurchaseInvoicesId" value="<?= $purchase_invoices_id ?>">
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id" , 'readonly' => 'true' , "size" => 30, "class" => "form-control"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Product ID :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["product_id", "type" => "number", "class" => "form-control", "id" => "fieldProductId"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Quantity :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Price :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="purchase_invoices_detail_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/purchase_invoices_detail/index/".$purchase_invoices_id, '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                        <?php echo $this->tag->linkTo(["backend/purchase_invoices_detail/delete/" . $id, '<button class="btn btn-danger icon-remove "><span class="glyphicon glyphicon-remove-circle"></span> Delete</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


