<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["purchase_invoices_detail", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create purchase_invoices_detail
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "purchase_invoices_detail/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPurchaseInvoicesId" class="col-sm-2 control-label">Purchase Of Invoices</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["purchase_invoices_id", "type" => "number", "class" => "form-control", "id" => "fieldPurchaseInvoicesId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductId" class="col-sm-2 control-label">Product</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_id", "type" => "number", "class" => "form-control", "id" => "fieldProductId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTotal" class="col-sm-2 control-label">Total</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["total", "size" => 30, "class" => "form-control", "id" => "fieldTotal"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedAt" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created_at", "size" => 30, "class" => "form-control", "id" => "fieldCreatedAt"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
