<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row" style="margin-left: 2%;">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/purchase_invoices_detail/index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thêm mới</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <div class="form-horizontal">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/purchase_invoices_detail/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "enctype" => "multipart/form-data"
                        ]
                    );
                    ?>
                    <div id="form-wizard-1" class="step">
                        <input style="visibility: hidden;display: none" name="purchase_invoices_id" id="fieldPurchaseInvoicesId" value="<?= $id ?>">
                        <div class="control-group">
                            <label class="control-label">Product ID :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["product_id", "type" => "number", "class" => "form-control", "id" => "fieldProductId"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Quantity :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Price :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="span12">
                                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default" ,  "style" => "float: right ;margin: 1%;"]) ?>
                            </div>
                        </div>

                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>
        </div>
    </div>


