<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>


<div class="panel-body">
    <div class="row-fluid" style="margin-left: 10%">
        <div class="span9">
            <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
                <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
                <div class="widget-box">
                    <div class="widget-content nopadding" style="margin-bottom: -2%;">
                        <?php
                        echo $this->tag->form(
                            [
                                "backend/producer/index",
                                "autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id" => "search_producer"
                            ]
                        );
                        ?>
                        <div class="control-group">
                            <label class="control-label">Id :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Company Name :</label>
                            <div class="controls">
                                <select name="company_name" id="company_name" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($page->items as $producer): ?>
                                        <option value="<?php echo $producer->company_name ?>"><?php echo $producer->company_name ?></option>
                                    <?php endforeach; ?>
                                </select>

                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Trademark :</label>
                            <div class="controls">
                                <select name="trademark" id="trademark" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($page->items as $producer): ?>
                                        <option value="<?php echo $producer->trademark ?>"><?php echo $producer->trademark ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Country Origin :</label>
                            <div class="controls">
                                <select name="trademark" id="trademark" style="border-radius: 4px">
                                    <option value="">Choose..</option>
                                    <?php foreach ($page->items as $producer): ?>
                                        <option value="<?php echo $producer->country_of_origin ?>"><?php echo $producer->country_of_origin ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Email :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldEmail"]) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Phone Number :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control",'style' => 'border-radius: 4px', "id" => "fieldPhoneNumber"]) ?>
                            </div>
                        </div>

                        <div class="hidden">
                            <label class="control-label"></label>
                            <div class="controls">
                                <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,  "id" => "submit-form"]) ?>
                            </div>
                        </div>
                        <?php echo $this->tag->endForm(); ?>
                        <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                            <label class="control-label"></label>
                            <div class="controls" style="float: right; margin-top: -5%;">
                                <?php echo $this->tag->linkTo(["backend/producer/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                                <button form="search_producer" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/producer/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Producer</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Company Name</th>
                <th style="background-color: #0288d1;color: #ffffff;">Trademark</th>
                <th style="background-color: #0288d1;color: #ffffff;">Country Origin</th>
                <th style="background-color: #0288d1;color: #ffffff;">Address</th>
                <th style="background-color: #0288d1;color: #ffffff;">Phone Of Number</th>
                <th style="background-color: #0288d1;color: #ffffff;">Email</th>
                <th style="background-color: #0288d1;color: #ffffff;">Website</th>

            </tr>
            <?php foreach ($page->items as $producer): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/producer/edit/" . $producer->id, $producer->id ]); ?></td>
                    <td><?php echo $producer->company_name ?></td>
                    <td><?php echo $producer->trademark ?></td>
                    <td><?php echo $producer->country_of_origin ?></td>
                    <td><?php echo $producer->address ?></td>
                    <td><?php echo $producer->phone_number ?></td>
                    <td><?php echo $producer->email ?></td>
                    <td><?php echo $producer->website ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>