<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="panel panel-primary" style=" border: 1px solid blue; background-color: blue; margin: 2%;">
            <h4 style="margin: -1%; padding: 1%;margin-bottom: -2%;color: white;">Tìm kiếm</h4>
            <div class="widget-box">
                <div class="widget-content nopadding" style="margin-bottom: -2%;">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/producer/index",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "id" => "search_producer"
                        ]
                    );
                    ?>
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Company Name :</label>
                        <div class="controls">
                            <select name="company_name" id="company_name">
                                <option value="">Choose..</option>
                                <?php foreach ($page->items as $producer): ?>
                                    <option value="<?php echo $producer->company_name ?>"><?php echo $producer->company_name ?></option>
                                <?php endforeach; ?>
                            </select>

                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Trademark :</label>
                        <div class="controls">
                            <select name="trademark" id="trademark">
                                <option value="">Choose..</option>
                                <?php foreach ($page->items as $producer): ?>
                                    <option value="<?php echo $producer->trademark ?>"><?php echo $producer->trademark ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Country Origin :</label>
                        <div class="controls">
                            <select name="trademark" id="trademark">
                                <option value="">Choose..</option>
                                <?php foreach ($page->items as $producer): ?>
                                    <option value="<?php echo $producer->country_of_origin ?>"><?php echo $producer->country_of_origin ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Email :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Phone Number :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", "id" => "fieldPhoneNumber"]) ?>
                        </div>
                    </div>

                    <div class="hidden">
                        <label class="control-label"></label>
                        <div class="controls">
                            <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,  "id" => "submit-form"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                    <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                        <label class="control-label"></label>
                        <div class="controls" style="float: right; margin-top: -5%;">
                            <?php echo $this->tag->linkTo(["backend/producer/index", '<button class="btn btn-info icon-repeat "><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                            <button form="search_producer" class="btn btn-info icon-search"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel-body">

    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/producer/new", ' <button class="btn btn-success"  style="margin-bottom: 5%;"><span class="glyphicon glyphicon-user"></span> Add New Producer</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th>Id</th>
                <th>Company Name</th>
                <th>Trademark</th>
                <th>Country Origin</th>
                <th>Address</th>
                <th>Phone Of Number</th>
                <th>Email</th>
                <th>Website</th>

            </tr>
            <?php foreach ($page->items as $producer): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/producer/edit/" . $producer->id, $producer->id ]); ?></td>
                    <td><?php echo $producer->company_name ?></td>
                    <td><?php echo $producer->trademark ?></td>
                    <td><?php echo $producer->country_of_origin ?></td>
                    <td><?php echo $producer->address ?></td>
                    <td><?php echo $producer->phone_number ?></td>
                    <td><?php echo $producer->email ?></td>
                    <td><?php echo $producer->website ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>