<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row" style="margin-left: 2%;">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/producer/index", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thêm mới</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <div class="form-horizontal">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/producer/create",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">Company Name :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["company_name", "size" => 30, "class" => "form-control", "id" => "fieldCompanyName"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Trademark :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["trademark", "size" => 30, "class" => "form-control", "id" => "fieldTrademark"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Country Of Origin :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["country_of_origin", "size" => 30, "class" => "form-control", "id" => "fieldCountryOfOrigin"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Address :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Website :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["website", "size" => 30, "class" => "form-control", "id" => "fieldWebsite"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Phone Number :</label>
                            <div class="controls">
                                <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", "id" => "fieldPhoneNumber"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Email :</label>
                            <div class="controls">
                                <?php echo $this->tag->emailField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="span12">
                                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default" ,  "style" => "float: right ;margin: 1%;"]) ?>
                            </div>
                        </div>

                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
            </div>
        </div>
    </div>



