<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["producer/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["producer/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Company Of Name</th>
            <th>Trademark</th>
            <th>Country Of Of Of Origin</th>
            <th>Address</th>
            <th>Phone Of Number</th>
            <th>Email</th>
            <th>Website</th>
            <th>Created</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $producer): ?>
            <tr>
                <td><?php echo $producer->id ?></td>
            <td><?php echo $producer->company_name ?></td>
            <td><?php echo $producer->trademark ?></td>
            <td><?php echo $producer->country_of_origin ?></td>
            <td><?php echo $producer->address ?></td>
            <td><?php echo $producer->phone_number ?></td>
            <td><?php echo $producer->email ?></td>
            <td><?php echo $producer->website ?></td>
            <td><?php echo $producer->created_at ?></td>

                <td><?php echo $this->tag->linkTo(["producer/edit/" . $producer->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["producer/delete/" . $producer->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("producer/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("producer/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("producer/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("producer/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
