<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["backend/description_product", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit description_product
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "backend/description_product/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstDescription" class="col-sm-2 control-label">First Of Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_description", "size" => 30, "class" => "form-control", "id" => "fieldFirstDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastDescription" class="col-sm-2 control-label">Last Of Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_description", "size" => 30, "class" => "form-control", "id" => "fieldLastDescription"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
