<main role="main">

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="/index/index" class="homepage-link" title="Back to the frontpage">Trang chủ</a>
                </li>

                <li class="current">
                    <a href="#">Tạo tài khoản</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End Breadcrumbs -->



    <div class="row">
        <div class="row">
            <div class="small-12 medium-12 large-12 columns">
                <div class="register">
                    <div id="customer">
                        <!-- Create Customer -->
                        <div id="create-customer">
                            <h1 class="page-title">Tạo tài khoản</h1>
                            <form id="create_customer" accept-charset="UTF-8">

                                <div class="row">
                                    <div class="large-6 columns" id="customer_full_name" class="clearfix large_form">
                                        <label for="customer_full_name" class="login">Họ và tên <span class="required">*</span></label>
                                        <input type="text" value="" name="customer_full_name" id="customer_full_name" class="large" size="30" />
                                    </div>
                                    <div class="large-6 columns" id="customer_phone_number" class="clearfix large_form">
                                        <label for="customer_phone_number" class="login">Số điện thoại <span class="required">*</span></label>
                                        <input type="text" value="" name="customer_phone_number" id="customer_phone_number" class="large" size="30" />
                                    </div>
                                    <div class="large-6 columns" id="email" class="clearfix large_form">
                                        <label for="email" class="login">Email</label>
                                        <input type="email" value="" name="customer_email" id="email" class="large" size="30" />
                                    </div>
                                    <div class="large-6 columns" id="address" class="clearfix large_form">
                                        <label for="address" class="login">Địa chỉ <span class="required">*</span></label>
                                        <input type="text" value="" name="customer_address" id="address" class="large" size="30" />
                                    </div>
                                    <div class="large-6 columns" id="passwords" class="clearfix large_form">
                                        <label for="password" class="login">Mật khẩu <span class="required">*</span></label>
                                        <input type="password" value="" name="customer_password" id="password" class="large password" size="30" />
                                    </div>
                                    <div class="large-6 columns" id="retype_password" class="clearfix large_form">
                                        <label for="retype_password" class="login">Nhập lại khẩu <span class="required">*</span></label>
                                        <input type="password" value="" name="retype_password" id="retype_password" class="large password" size="30" />
                                    </div>
                                </div>
                                <div>
                                    <input class="button" type="submit" value="Đăng ký" />
                                </div>
                                <div class="account_des_notes">

                                    Bạn có sẵn sàng tạo một tài khoản? <a href="/account/login" id="customer_login_link">Đăng nhập</a> Hoặc <a href="/index/index">Quay lại trang chủ</a>

                                </div>
                            </form>
                        </div>
                        <!-- /#create-customer -->
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>