<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="vn" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="vn" > <!--<![endif]-->

<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <?php echo $this->tag->getTitle(); ?>


    <meta name="description" content="Watches Store" />
    <script>window.ShopifyPaypalV4VisibilityTracking = true;</script>
    <script type="text/javascript">
        //<![CDATA[
        var Shopify = Shopify || {};
        Shopify.shop = "ap-best-store.myshopify.com";
        Shopify.theme = {"name":"bestwatches","id":9620096,"theme_store_id":null,"role":"main"};
        Shopify.theme.handle = "null";
        Shopify.theme.style = {"id":null,"handle":null};

        //]]>
    </script><script type="text/javascript">
        //<![CDATA[
        (function() {
            function asyncLoad() {
                var urls = ["\/\/productreviews.shopifycdn.com\/assets\/v4\/spr.js?shop=ap-best-store.myshopify.com"];
                for (var i = 0; i < urls.length; i++) {
                    var s = document.createElement('script');
                    s.type = 'text/javascript';
                    s.async = true;
                    s.src = urls[i];
                    var x = document.getElementsByTagName('script')[0];
                    x.parentNode.insertBefore(s, x);
                }
            };
            if(window.attachEvent) {
                window.attachEvent('onload', asyncLoad);
            } else {
                window.addEventListener('load', asyncLoad, false);
            }
        })();

        //]]>
    </script><script id="__st">
        //<![CDATA[
        var __st={"a":7503913,"offset":-18000,"reqid":"8cd0c4af-d13a-4d4b-b3f3-f94f056334f3","pageurl":"ap-best-store.myshopify.com\/","u":"4cd816547d80","p":"home"};
        //]]>
    </script>
    <meta id="shopify-digital-wallet" name="shopify-digital-wallet" content="/7503913/digital_wallets/dialog" />

    <script type="text/javascript">

        window.ShopifyAnalytics = window.ShopifyAnalytics || {};
        window.ShopifyAnalytics.meta = window.ShopifyAnalytics.meta || {};
        window.ShopifyAnalytics.meta.currency = 'USD';
        var meta = {"page":{"pageType":"home"}};
        for (var attr in meta) {
            window.ShopifyAnalytics.meta[attr] = meta[attr];
        }

    </script>

    <script type="text/javascript">
        window.ShopifyAnalytics.merchantGoogleAnalytics = function() {

        };
    </script>

    <script type="text/javascript" class="analytics">



        (function () {
            var customDocumentWrite = function(content) {
                var jquery = null;

                if (window.jQuery) {
                    jquery = window.jQuery;
                } else if (window.Checkout && window.Checkout.$) {
                    jquery = window.Checkout.$;
                }

                if (jquery) {
                    jquery('body').append(content);
                }
            };

            var trekkie = window.ShopifyAnalytics.lib = window.trekkie = window.trekkie || [];
            if (trekkie.integrations) {
                return;
            }
            trekkie.methods = [
                'identify',
                'page',
                'ready',
                'track',
                'trackForm',
                'trackLink'
            ];
            trekkie.factory = function(method) {
                return function() {
                    var args = Array.prototype.slice.call(arguments);
                    args.unshift(method);
                    trekkie.push(args);
                    return trekkie;
                };
            };
            for (var i = 0; i < trekkie.methods.length; i++) {
                var key = trekkie.methods[i];
                trekkie[key] = trekkie.factory(key);
            }
            trekkie.load = function(config) {
                trekkie.config = config;
                var script = document.createElement('script');
                script.type = 'text/javascript';
                script.onerror = function(e) {
                    (new Image()).src = 'http://v.shopify.com/internal_errors/track?error=trekkie_load';
                };
                script.async = true;
                script.src = '/public/js/trekkie.storefront.min97e4.js?v=2017.09.05.1';
                var first = document.getElementsByTagName('script')[0];
                first.parentNode.insertBefore(script, first);
            };
            trekkie.load(
                {"Trekkie":{"appName":"storefront","development":false,"defaultAttributes":{"shopId":7503913,"isMerchantRequest":null,"themeId":9620096,"themeCityHash":16582298854200938285}},"Performance":{"navigationTimingApiMeasurementsEnabled":true,"navigationTimingApiMeasurementsSampleRate":0.1},"Session Attribution":{}}
            );

            var loaded = false;
            trekkie.ready(function() {
                if (loaded) return;
                loaded = true;

                window.ShopifyAnalytics.lib = window.trekkie;


                var originalDocumentWrite = document.write;
                document.write = customDocumentWrite;
                try { window.ShopifyAnalytics.merchantGoogleAnalytics.call(this); } catch(error) {};
                document.write = originalDocumentWrite;


                window.ShopifyAnalytics.lib.page(
                    null,
                    {"pageType":"home"}
                );


            });


            var eventsListenerScript = document.createElement('script');
            eventsListenerScript.async = true;
            eventsListenerScript.src = "/public/js/shop_events_listener-f2c5800305098f0ebebdfa7d980c9abf56514c46d5305e97a7c476f7c9116163.js";
            document.getElementsByTagName('head')[0].appendChild(eventsListenerScript);

        })();
    </script>

    <script src="/public/js/express_buttons-5a0b9f68e3c8f7b5c3088995ef0bdcea74699f4e5b29d93780dc74e6832017a5.js" defer="defer" crossorigin="anonymous" ></script><script>
        //<![CDATA[
        window.Shopify = window.Shopify || {};
        window.Shopify.Checkout = window.Shopify.Checkout || {};
        window.Shopify.Checkout.apiHost = "ap-best-store.myshopify.com";
        window.Shopify.Checkout.rememberMeHost = "pay.shopify.com";
        window.Shopify.Checkout.rememberMeAccessToken = "Nk04aUxweVo4ajJrd09ML2FtNmVMYlVWdXF2bDBHY2FPbkorSVlQalRXcmZ3OVBCdzJiZ1dvYnJnNVc4VFlzbC0tRElNYmFwbzI0OFljQy9VMjZuYzJSdz09--0b59837175bb7536302f69e209e592ec6468199e";
        window.Shopify.Checkout.sheetStyleSheetUrl = "\/\/cdn.shopify.com\/s\/assets\/shared\/sheet\/main-c38a91ed541a82b485cb4285b3651975cfbf14dd4524647e78a9715f2c79e28b.css";

        //]]>
    </script>

    <!-- CSS -->
    <link href="/public/css/fontse0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/font-awesome.min.css" rel="stylesheet">
    <link href="/public/css/responsive.scsse0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/normalizee0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/stylee0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/font-awesome.mine0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/foundation-iconse0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/custome0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/owl.carousele0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/owl.themee0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <link href="/public/css/jquery.alerts.css" rel="stylesheet" type="text/css" media="all" />

    <!-- Ajaxify Cart Plugin ================================================== -->
    <link href="/public/css/ajaxify.scsse0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />


    <link href="/public/css/retina-responsivee0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />

    <!-- JS -->
    <script src="/public/js/html5shive0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/jquery.min.js" type="text/javascript"></script>
    <script src="/public/js/custom.modernizre0a9.js?4621688722820174607" type="text/javascript"></script>
    <link href="/public/css/animatee0a9.css?4621688722820174607" rel="stylesheet" type="text/css" media="all" />
    <script src="/public/js/wow.mine0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/owl.carousel.mine0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/modernizr.custome0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/classiee0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/uisearche0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/maine0a9.js?4621688722820174607" type="text/javascript"></script>
    <script src="/public/js/jquery.validate.min.js" type="text/javascript"></script>

    <script src="/public/js/option_selection-ea4f4a242e299f2227b2b8038152223f741e90780c0c766883939e8902542bda.js" type="text/javascript"></script>
    <script src="/public/js/modernizr.mine0a9.js?4621688722820174607" type="text/javascript"></script>
    <!-- Icons -->

    <link rel="shortcut icon" href="/public/files/favicone0a9.html?4621688722820174607" type="image/x-icon" />

    <!-- Facebook Open Graph -->

    <meta property="og:title" content="Best Watches Store"/>
    <meta property="og:type" content="article"/>
    <meta property="og:image" content="//public/img/logo.png?4621688722820174607"/>
    <meta property="og:url" content="https://ap-best-store.myshopify.com"/>

    <meta property="og:site_name" content="Best Watches Store"/>
    <link rel="canonical" href="index.html">
</head>
<body class="collection antialiased off-canvas-wrap header-default  layout-default"  id="responsive-shopify-theme" data-offcanvas>
<div class="inner-wrap">
    <!-- header menu small -->
    <?php $this->partial('index/mobile _header_menu') ?>
    <!-- end header menu small -->
    <section class="main-section">

        <!-- header menu -->
        <?php $this->partial('index/top_menu') ?>
        <!-- end header menu -->


        <?php echo $this->getContent(); ?>



        <footer role="contentinfo">
            <div class="footer-wrapper">
                <div class="row">
                    <div class="footer">
                        <div class="row">

                            <!-- Begin footer navigation -->

                            <div class="small-12 medium-6 large-3 columns text-center wow fadeInUp animated" data-wow-delay="0.5s">
                                <h4>LIÊN KẾT</h4>
                                <ul class="unstyled">

                                    <li><a href="#" title="Thông tin liên lạcs">Thông tin liên lạc</a></li>

                                    <li><a href="#" title="Trợ giúp & Hỏi đáp">Trợ giúp & Hỏi đáp</a></li>

                                    <li><a href="#" title="Vận chuyển & Trả hàng">Vận chuyển & Trả hàng</a></li>

<!--                                    <li><a href="pages/wish-list.html" title="Wist list">Wist list</a></li>-->

                                </ul>
                            </div>

                            <!-- End footer navigation -->

                            <!-- Begin footer contact info -->
                            <div class="small-12 medium-6 large-3 columns text-center wow fadeInUp animated" data-wow-delay="0.3s">
                                <h4>THÔNG TIN LIÊN LẠC</h4>
                                <p>Hà nội , Việt Nam<br>
                                    +084) 0167 272 9181<br>
                                    Email: huuquynh142@gmail.com<br></p>
                            </div>
                            <!-- End footer contact info -->

                            <!-- Begin footer newletter -->
                            <div class="small-12 medium-6 large-3 columns text-center wow fadeInUp animated" data-wow-delay="0.3s">
                                <h4>THAM GIA CÙNG CHÚNG TÔI</h4>
                                <p class="des">Đăng ký nhận bản tin của chúng tôi và nhận phiếu giảm giá với chiết khấu</p>
                                <form action="#" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank">
                                    <input type="email" value="" placeholder="Địa chỉ email" name="EMAIL" id="mail" /><input type="submit" class="btn newsletter" value="Subscribe" name="subscribe" id="subscribe" />
                                </form>
                            </div>
                            <!-- End footer newletter -->

                            <!-- Begin footer payment -->
                            <div class="small-12 medium-6 large-3 columns text-center payment wow fadeInUp animated" data-wow-delay="0.5s">
                                <h4>CHẤP NHẬN THANH TOÁN</h4>
                                <p><img src="/public/img/paymente0a9.png?4621688722820174607" alt="" /></p>
                            </div>
                            <!-- End footer payment -->

                        </div>
                    </div>
                    <div class="coppy-right">
                        <div class="row">
                            <div class="large-12 columns text-center wow fadeInUp animated" data-wow-delay="0.3s">
                                <a href="#" title="Best Watches Store on Twitter" class="icon-social twitter"><i class="fa fa-twitter"></i></a>
                                <a href="#" title="Best Watches Store on Facebook" class="icon-social facebook"><i class="fa fa-facebook"></i></a>






                                <a href="#" title="Best Watches Store on Google+" class="icon-social google"><i class="fa fa-google-plus"></i></a>
                            </div>
                            <div class="large-12 columns text-center ">
                                <div class="powered">
                                    <p align="center">&copy; Copyright 2018 Best Watches Store. </p>
<!--                                    <a target="_blank" rel="nofollow" href="https://www.shopify.com/">Powered by Shopify</a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>



        <script>
            wow = new WOW(
                {
                    boxClass:     'wow',      // default
                    animateClass: 'animated', // default
                    offset:       0          // default
                }
            )
            wow.init();
        </script>
    </section>
    <a class="exit-off-canvas"></a>
</div>
<p id="back-top">
    <a href="#top" title="Scroll To Top">Scroll To Top</a>
</p>

<div id="paneltool">
    <div class="paneltool">
        <div class="panelbutton hidden-sm">
            <img src="http://cdn.shopify.com/s/files/1/0750/3913/t/2/assets/params.svg?4621688722820174607" alt="" />
        </div>
        <div class="panelcontent ">
            <div class="panelinner">
                <span>Panel Tool</span>
                <div class="group-input clearfix">
                    <label class="control-label"><img src="http://cdn.shopify.com/s/files/1/0750/3913/t/2/assets/pin.svg?4621688722820174607" alt="" /> Float style</label>
                    <div class="paneltool-update">
                        <span class="control-span">Float header</span>
                        <div class="float-control">
                            <div class="onoffswitch">
                                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="floatHeader" >
                                <label class="onoffswitch-label" for="floatHeader">
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="paneltool-update">
                        <span class="control-span">Float topbar</span>
                        <div class="float-control">
                            <div class="onoffswitch">
                                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="floatTopbar" >
                                <label class="onoffswitch-label" for="floatTopbar">
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="group-input clearfix">
                    <label class="control-label"><i class="fa fa-desktop"></i> Layout mode</label>
                    <div class="layout-control clearfix">
                        <span class="dynamic-update-layout paneltool-update selected" data-layout-mode="layout-default">Default</span>
                        <span class="dynamic-update-layout paneltool-update " data-layout-mode="layout-boxed-lg">Boxed Large</span>
                        <span class="dynamic-update-layout paneltool-update " data-layout-mode="layout-boxed-md">Boxed Medium</span>
                    </div>
                </div>
                <div class="group-input clearfix">
                    <label class="control-label"><i class="fa fa-header"></i> Header mode</label>
                    <div class="layout-control clearfix">
                        <span class="dynamic-update-header paneltool-update selected" data-header-style="header-default">Header Default</span>
                        <span class="dynamic-update-header paneltool-update " data-header-style="header-one">Header One</span>
                        <span class="dynamic-update-header paneltool-update " data-header-style="header-two">Header Two</span>
                        <span class="dynamic-update-header paneltool-update " data-header-style="header-three">Header Three</span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/public/js/foundation.mine0a9.js?4621688722820174607" type="text/javascript"></script>
<script>
    $(document).foundation({
        orbit: {

            pause_on_hover: true,


            timer_speed: 10000

        }
    });
</script>
<!-- Product Image JS by @lukebussey -->
<script src="/public/js/productimagese0a9.js?4621688722820174607" type="text/javascript"></script>
<!-- Let's add a product zoom becaue Foundation doesn't have one. Thank's to Jack Moore! -->
<script src="/public/js/jquery.zoome0a9.js?4621688722820174607" type="text/javascript"></script>
<script src="/public/js/shope0a9.js?4621688722820174607" type="text/javascript"></script>
<script src="/public/js/myfrontend.js" type="text/javascript"></script>
<script src="/public/js/jquery.alerts.js" type="text/javascript"></script>

<script src="/public/js/currencies.js" type="text/javascript"></script>
<script src="/public/js/jquery.currencies.mine0a9.js?4621688722820174607" type="text/javascript"></script>
<script>
    // Pick your format here:
    // Can be 'money_format' or 'money_with_currency_format'
    Currency.format = 'money_format';
    var shopCurrency = 'USD';
    var cookieCurrency = Currency.cookie.read();
    // Fix for customer account pages
    jQuery('span.money span.money').each(function() {
        jQuery(this).parent('span.money').removeClass('money');
    });
    // Add precalculated shop currency to data attribute
    jQuery('span.money').each(function() {
        jQuery(this).attr('data-currency-USD', jQuery(this).html());
    });
    // Select all your currencies buttons.
    var buttons = jQuery('#currencies a');
    var currentCurrencies = jQuery('.currencies-current > a');
    // When the page loads.
    if (cookieCurrency == null || cookieCurrency == shopCurrency) {
        Currency.currentCurrency = shopCurrency;
    }
    else {
        Currency.currentCurrency = cookieCurrency;
        Currency.convertAll(shopCurrency, cookieCurrency);
        buttons.removeClass('selected');
        jQuery('#currencies a[data-currency=' + cookieCurrency + ']').addClass('selected');
        do_multi_currency_warning(Currency.currentCurrency, shopCurrency);
    }
    // When customer clicks on a currency button.
    buttons.click(function() {
        buttons.removeClass('selected');
        jQuery(this).addClass('selected');
        var newCurrency =  jQuery(this).attr('data-currency');
        currentCurrencies.html(newCurrency + '<i class="fa fa-angle-down"></i>');
        Currency.convertAll(Currency.currentCurrency, newCurrency);
        do_multi_currency_warning(Currency.currentCurrency, shopCurrency);
    });
    // For product options.
    var original_selectCallback = window.selectCallback;
    var selectCallback = function(variant, selector) {
        original_selectCallback(variant, selector);
        Currency.convertAll(shopCurrency, jQuery('#currencies a.selected').attr('data-currency'));
        do_multi_currency_warning(Currency.currentCurrency, shopCurrency);
    };
    // do this each time you recalculate or page load
    do_multi_currency_warning(Currency.currentCurrency, shopCurrency);
    // a function to make the cart better when choosing different currencies
    // explained in step 7 below
    function do_multi_currency_warning(currentCurrency, shopCurrency)
    {
        jQuery('.selected-currency').text(Currency.currentCurrency);
        if (currentCurrency != shopCurrency){
            jQuery('.multi-currency-warning').text('*');
            jQuery('.multi-currency-warning-bottom').show();
        }
        else{
            jQuery('.multi-currency-warning').text('');
            jQuery('.multi-currency-warning-bottom').hide();
        }
    }
</script>


<script src="/public/js/handlebars.mine0a9.js?4621688722820174607" type="text/javascript"></script>
<script src="/public/js/ajaxifye0a9.js?4621688722820174607" type="text/javascript"></script>



<script src="/public/js/retinae0a9.js?4621688722820174607" type="text/javascript"></script>

</body>

<!-- Mirrored from ap-best-store.myshopify.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Jan 2018 06:18:58 GMT -->
</html>
