<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search product_credential
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["product_credential/new", "Create product_credential"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "product_credential/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductId" class="col-sm-2 control-label">Product</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_id", "type" => "number", "class" => "form-control", "id" => "fieldProductId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductTypeId" class="col-sm-2 control-label">Product Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_type_id", "type" => "number", "class" => "form-control", "id" => "fieldProductTypeId"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
