<main role="main">

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="/trang-chu" class="homepage-link" title="Back to the frontpage">Home</a>
                </li>
                <li>
                    <a href="/san-pham" title="">Sản phẩm</a>
                </li>
                <li class="current">
                    <a href="#"><?= $productDetail[0]->product_name ?></a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End Breadcrumbs -->


    <div id="product-details" itemscope itemtype="http://schema.org/Product">
        <meta itemprop="url" content="https://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot" />
        <meta itemprop="image" content="//cdn.shopify.com/s/files/1/0750/3913/products/5_2f0effb3-31ab-47fa-bcb7-15664aeba7ef_grande.jpeg?v=1421825327" />
        <div class="product-view">
            <div class="row">
                <div id="product-images" class="large-5 columns" >
                    <div id="zoom-collections-women-products-jessica-simpson-womens-allest-boot" class="pro-zoom">
                        <img src="/public/img/product/<?= $productDetail[0]->image ?>" alt="Jessica Simpson Women&#39;s Allest Boot" id="product_feature_image" />
                    </div>

                    <ul id="product_thumbs" class="product_thumbs">

                        <?php
                        if (sizeof($productImage ) > 1)
                            foreach ($productImage as $product_image): ?>
                                <li><a class="thumb" href="/public/img/product/<?= $product_image->image ?>" title="Jessica Simpson Women's                 Allest Boot"><img class="lazyOwl" data-src="/public/img/product/<?= $product_image->image ?>" alt=""></a></li>
                            <?php endforeach; ?>

                    </ul>

                </div>
                <script>
                    $(document).ready(function(){
                        $('#zoom-collections-women-products-jessica-simpson-womens-allest-boot').zoom();
                        $('#grab-collections-women-products-jessica-simpson-womens-allest-boot').zoom({ on:'grab' });
                        $('#click-collections-women-products-jessica-simpson-womens-allest-boot').zoom({ on:'click' });
                        $('#toggle-collections-women-products-jessica-simpson-womens-allest-boot').zoom({ on:'toggle' });
                    });
                </script>
                <div id="product-shop" class="large-7 columns">
                    <div class="product-title">
                        <h1 itemprop="name"><?= $productDetail[0]->product_name ?></h1>
                        <span>MSP : <?= $productDetail[0]->description_id ?></span>

                    </div>

                    <div class="review">
                        <span class="shopify-product-reviews-badge" data-id="408538376"></span>
                    </div>

<!--                    <div class="product-description" class="rte des" itemprop="description">-->
<!--                        The standard Lorem Ipsum passage...-->
<!--                    </div>-->
                    <div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="priceCurrency" content="USD" />

                        <link itemprop="availability" href="http://schema.org/InStock" />

                        <h5>
                        <span id="productPrice" class="h1">







<small></small>
                        </span>

                        </h5>
                    </div>
<!--                    <h5 class="brand" itemprop="brand"><a href="https://ap-best-store.myshopify.com/collections/vendors?q=Apple%2C%20Shopify" title="">Apple, Shopify</a></h5>-->
                        <div id="product-add">
                            <div class="qty-adder qty-adder408538376 pull-left">
                                <div class="quantity-number pull-left">
                                    <a href="javascript:void(0)" title=""><span class="add-down add-action">-</span></a>
                                    <input class="quantity_<?= $productDetail[0]->id ?>" id="quantity" type="text" name="quantity" size="2" value="1">
                                    <a href="javascript:void(0)" title=""><span class="add-up add-action">+</span></a>
                                </div>
                            </div>
                            <button type="submit" data-id="<?= $productDetail[0]->id ?>" name="add" id="addToCart" class="btn">
                                <span class="fa fa-shopping-cart"></span>
                                <span id="addToCartText">Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <span id="variantQuantity" class="variant-quantity"></span>

                    <div class="wishlist_des">Để thêm vào danh sách mong muốn bạn cần phải <a href="/dang-nhap">đăng nhập</a> hoặc <a href="/dang-ky">đăng ký</a>.</div>


                    <!-- Sharing is caring -->

                    <div class="large-12 columns">
                        <br />
                        <ul class="social-sharing inline-list">
                            <li>Chia sẻ: </li>
                            <li><a target="_blank" href="https://twitter.com/intent/tweet?text=Jessica%20Simpson%20Women's%20All...&amp;url=http%3A%2F%2Fap-best-store.myshopify.com%2Fproducts%2Fjessica-simpson-womens-allest-boot&amp;via=rcinteriors"><i class="fi-social-twitter"></i></a></li>
                            <li><a target="_blank" href="http://www.facebook.com/sharer/sharer.php?u=http://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot"><i class="fi-social-facebook"></i></a></li>
                            <li><a target="_blank" href="https://plus.google.com/share?url=http://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot"><i class="fi-social-google-plus"></i></a></li>
                            <li><a target="_blank" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=http://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot&amp;title=Jessica%20Simpson%20Women's%20All...&amp;summary=The%20standard%20Lorem%20Ipsum%20passage,%20used%20since%20the%201500s"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco...&source=http://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot"><i class="fi-social-linkedin"></i></a></li>
                            <li><a target="_blank" href="http://pinterest.com/pin/create/button/?url=http://ap-best-store.myshopify.com/products/jessica-simpson-womens-allest-boot&amp;description=The%20standard%20Lorem%20Ipsum%20passage,%20used%20since%20the%201500s"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco...&media=//cdn.shopify.com/s/files/1/0750/3913/products/5_2f0effb3-31ab-47fa-bcb7-15664aeba7ef_large.jpeg?v=1421825327"><i class="fi-social-pinterest"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="product-tabs">
                    <dl class="tabs" data-tab>
                        <dd class="active"><a href="#panel1">Thông tin chi tiết</a></dd>
                    </dl>
                    <div class="tabs-content">
                        <div class="content active des" id="panel1">
                            <table>
                                <tr>
                                    <td>Tên sản phẩm</td>
                                    <td><?= $productDetail[0]->product_name ?></td>
                                </tr>
                                <tr>
                                    <td>Mã sản phẩm</td>
                                    <td><?= $productDetail[0]->description_id ?></td>
                                </tr>
                                <tr>
                                    <td>Thương hiệu</td>
                                    <td><?= $productDetail[0]->company_name ?></td>
                                </tr>
                                <tr>
                                    <td>Chất liệu vỏ</td>
                                    <td><?= $productDetail[0]->shell_material ?></td>
                                </tr>
                                <tr>
                                    <td>Chất liệu dây</td>
                                    <td><?= $productDetail[0]->wire_material ?></td>
                                </tr>
                                <tr>
                                    <td>Mắt kính</td>
                                    <td><?= $productDetail[0]->glasses ?></td>
                                </tr>
                                <tr>
                                    <td>Đường kính vỏ</td>
                                    <td><?= $productDetail[0]->shell_diameter ?></td>
                                </tr>
                                <tr>
                                    <td>Độ dày vỏ</td>
                                    <td><?= $productDetail[0]->shell_thickness ?></td>
                                </tr>
                                <tr>
                                    <td>Chống nước</td>
                                    <td><?= $productDetail[0]->water_resistant ?></td>
                                </tr>
                                <tr>
                                    <td>Loại đồng hồ</td>
                                    <td><?= $productDetail[0]->is_electronic ? 'Điện tử' : 'Cơ' ?></td>
                                </tr>
                                <tr>
                                    <td>Động cơ</td>
                                    <td><?= $productDetail[0]->motor ?></td>
                                </tr>
                                <tr>
                                    <td>Bảo hành</td>
                                    <td><?= $productDetail[0]->guarantee ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">








            <div class="related-products box carousel">

                <div class="box-title">
                    <h3>Sản phẩm tương tự</h3>
                    <span class="abs"><i class="fa fa-headphones"></i></span>
                </div>


                <div class="box-content">

                    <div id="related-products" class="row products-row owl-control">

                        <?php $this->partial("productdetail/relatedproducts") ?>

                    </div>
                </div>
            </div>

            <script>
                $(document).ready(function() {
                    $("#related-products").owlCarousel({
                        items : 5,
                        autoPlay : true,
                        stopOnHover : true,
                        pagination : false,

                        // Navigation
                        navigation : true,
                        navigationText : ["prev","next"],
                        rewindNav : true,
                        scrollPerPage : false,
                    });

                    $(".lazyOwl").parent().click(function(e) {
                        e.preventDefault();
                        var follower_user_id = $(this).attr('href');
                        $(".pro-zoom img").attr("src",follower_user_id);
                        return false;
                    });

                })
            </script>

        </div>

    </div>
    <script>
        $(document).ready(function() {
            $("#product_thumbs").owlCarousel({
                items : 4, //10 items above 1000px browser width
                itemsDesktop : [1000,4], //5 items between 1000px and 901px
                itemsDesktopSmall : [900,4], // betweem 900px and 601px
                itemsTablet: [600,4], //2 items between 600 and 0
                itemsMobile : false,
                autoPlay : false,
                lazyLoad : true,
                stopOnHover : true,
                pagination : false
            });
            console.log('ABCD-DEMO + ' + true );

            $('.single-option-selector:eq(0)').val("X").trigger('change');

            $('.single-option-selector:eq(1)').val("Red").trigger('change');



            $(".qty-adder408538376 .add-action").click( function(){
                if( $(this).hasClass('add-up') ) {
                    $("[name=quantity]",'.qty-adder408538376').val( parseInt($("[name=quantity]",'.qty-adder408538376').val()) + 1 );
                }else {
                    if( parseInt($("[name=quantity]",'.qty-adder408538376').val())  > 1 ) {
                        $("input",'.qty-adder408538376').val( parseInt($("[name=quantity]",'.qty-adder408538376').val()) - 1 );
                    }
                }
            });
        });
    </script>

</main>