<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user_information", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit user_information
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user_information/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["user_id", "type" => "number", "class" => "form-control", "id" => "fieldUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDepartmentId" class="col-sm-2 control-label">Department</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["department_id", "type" => "number", "class" => "form-control", "id" => "fieldDepartmentId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSex" class="col-sm-2 control-label">Sex</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sex", "type" => "number", "class" => "form-control", "id" => "fieldSex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhoneNumber" class="col-sm-2 control-label">Phone Of Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", "id" => "fieldPhoneNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAvartar" class="col-sm-2 control-label">Avartar</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["avartar", "size" => 30, "class" => "form-control", "id" => "fieldAvartar"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
