<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user_information/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user_information/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>User</th>
            <th>Department</th>
            <th>Last Of Name</th>
            <th>First Of Name</th>
            <th>Sex</th>
            <th>Address</th>
            <th>Phone Of Number</th>
            <th>Email</th>
            <th>Avartar</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user_information): ?>
            <tr>
                <td><?php echo $user_information->id ?></td>
            <td><?php echo $user_information->user_id ?></td>
            <td><?php echo $user_information->department_id ?></td>
            <td><?php echo $user_information->last_name ?></td>
            <td><?php echo $user_information->first_name ?></td>
            <td><?php echo $user_information->sex ?></td>
            <td><?php echo $user_information->address ?></td>
            <td><?php echo $user_information->phone_number ?></td>
            <td><?php echo $user_information->email ?></td>
            <td><?php echo $user_information->avartar ?></td>

                <td><?php echo $this->tag->linkTo(["user_information/edit/" . $user_information->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user_information/delete/" . $user_information->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user_information/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("user_information/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("user_information/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("user_information/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
