<!DOCTYPE html>
<html lang="en">

<head>
        <title>Matrix Admin</title><meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="/public/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/public/css/bootstrap-responsive.min.css" />
        <link rel="stylesheet" href="/public/css/matrix-login.css" />
        <link href="/public/css/font-awesome.css" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <div id="loginbox">
            <?php
            echo $this->tag->form(
                [
                    "/../../backend/security/save",
                    "autocomplete" => "off",
                    "class" => "form-vertical"
                ]
            );
            ?>
				 <div class="control-group normal_text"> <h3><img src="/public/img/logobackend.png" alt="Logo" /></h3></div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lg"><i class="icon-user"> </i></span><input type="text" name="user_name" id="user_name" placeholder="Username" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly"><i class="icon-lock"></i></span><input type="password" name="password" id="password" placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-info" id="to-recover">Lost password?</a></span>
                    <span class="pull-right"> <?php echo $this->tag->submitButton(["Login", "id" => "btl_login" , "class" => "btn btn-success" ]) ?></span>
                </div>
            <?php echo $this->tag->endForm(); ?>

        </div>

        <script src="/public/js/jquery.min.js"></script>
        <script src="/public/js/matrix.login.js"></script>
        <script src="/public/js/mybackend.js"></script>
    </body>

</html>
