<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="panel panel-primary" style=" border: 1px solid #0288d1; background-color: #0288d1; margin: 2%; border-radius: 4px;">
            <h5 style="margin: -1%; padding: 8px;margin-bottom: -3%;color: white;">Tìm kiếm</h5>
            <div class="widget-box">
                <div class="widget-content nopadding" style="margin-bottom: -2%;">
                    <?php
                    echo $this->tag->form(
                        [
                            "backend/product_image/index",
                            "autocomplete" => "off",
                            "class" => "form-horizontal",
                            "id" => "search_img"
                        ]
                    );
                    ?>
                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control" , 'style' => 'border-radius: 4px', "id" => "fieldId"]) ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">product Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["productId", "type" => "number", "class" => "form-control" , 'style' => 'border-radius: 4px', "id" => "fieldProductId"]) ?>
                        </div>
                    </div>
                    <div class="hidden">
                        <label class="control-label"></label>
                        <div class="controls">
                            <?php echo $this->tag->submitButton(["Save", "class" => "hidden" ,'style' => 'border-radius: 4px',  "id" => "submit-form"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                    <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                        <label class="control-label"></label>
                        <div class="controls" style="float: right; margin-top: -5%;">
                            <?php echo $this->tag->linkTo(["backend/product_image/index", '<button class="btn btn-info icon-repeat " style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Reset</button>']); ?>
                            <button form="search_img" class="btn btn-info icon-search" style="border-radius: 4px;"><span class="glyphicon glyphicon-remove-circle"></span> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="panel-body">

    <div class="col-lg-12" style="padding-left: 0; padding-right: 0;" >
        <div class="pull-right"><?php echo $this->tag->linkTo(["backend/product_image/new", ' <button class="btn btn-success"  style="margin-bottom: 5%; border-radius: 4px;"><span class="glyphicon glyphicon-user"></span> Add New Image</button>']); ?>
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">product id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Image</th>

            </tr>
            <?php foreach ($page->items as $product_image): ?>
                <tr>
                    <td><?php echo $this->tag->linkTo(["backend/product_image/edit/" . $product_image->id, $product_image->id ]); ?></td>
                    <td><?php echo $product_image->product_id ?></td>
<!--                    <td>--><?php //echo $product_image->member ?><!--</td>-->
                    <td><?php echo $this->tag->image(['public/img/product/'.$product_image->image , "alt" => " alt member " , "style" => "width: 100px;height: 100px;" ]) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
