<div class="main__content">

    <div class="step" data-step="thank-you">
        <div class="section">
            <div class="section__header os-header">
                <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#000" stroke-width="2" class="os-header__hanging-icon checkmark">
                    <path class="checkmark__circle" d="M25 49c13.255 0 24-10.745 24-24S38.255 1 25 1 1 11.745 1 25s10.745 24 24 24z"></path>
                    <path class="checkmark__check" d="M15 24.51l7.307 7.308L35.125 19"></path>
                </svg>

                <div class="os-header__heading">
                    <h2 class="os-header__title">
                        Cảm ơn bạn đã sử dụng dịch vụ của best watchs !
                    </h2>
                </div>
            </div>
        </div>


        <div class="section">
            <div class="section__content">

                <div class="content-box">
                    <div class="content-box__row content-box__row--no-border">
                        <h2>Thông tin khách hàng</h2>
                    </div>
                    <div class="content-box__row">
                        <div class="section__content">
                            <div class="section__content__column section__content__column--half">
                                <h3>Địa chỉ nhận hàng</h3>
                                <address class="address">
                                    Họ tên : <span><?= $infconfirm[0]->fullname ?></span>
                                    <br>
                                    Số điện thoại : <span><?= $infconfirm[0]->phone ?></span>
                                    <br>
                                    Địa chỉ : <span><?= $infconfirm[0]->address ?></span>
                                    <br>
                                    Quận/Huyện : <span><?= $infconfirm[0]->district ?></span>
                                    <br>
                                    Tỉnh/Thành phố : <span><?= $infconfirm[0]->province ?></span>
                                </address>
                                <h3>Hình thức vận chuyển</h3>
                                <p>Vận chuyển tiêu chuẩn : <span><?= number_format($infconfirm[0]->shipping ,0  , 0 , '.').' VND'  ?></span></p>
                            </div>
                            <div class="section__content__column section__content__column--half">
                                <h3>Hình thức thanh toán</h3>
                                <ul class="payment-method-list">
                                    <li class="payment-method-list__item">
                                        <span class="payment-method-list__item__info"><?= $infconfirm[0]->pay_method_id == 1 ? 'Thanh toán trả sau' : 'Thanh toán online' ?></span>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="step__footer">
        <a href="/trang-chu" class="step__footer__continue-btn btn">
            <span class="btn__content">Tiếp tục mua hàng</span>
            <svg class="icon-svg icon-svg--size-18 btn__spinner icon-svg--spinner-button" aria-hidden="true" focusable="false"> <use xlink:href="#spinner-button"></use> </svg>
        </a>
        <p class="step__footer__info">
            <svg aria-hidden="true" focusable="false" class="icon-svg icon-svg--color-adaptive-lighter icon-svg--size-18 icon-svg--inline-before"> <use xlink:href="#question-circle"></use> </svg>
            <span>
      Bạn cần trợ giúp? <a href="mailto:huuquynh@gmail.com">Liên hệ với chúng tôi</a>
    </span>
        </p>
    </div>


    <span class="visually-hidden" id="forwarding-external-new-window-message">
  Opens external website in a new window.
</span>

    <span class="visually-hidden" id="forwarding-new-window-message">
  Opens in a new window.
</span>

    <span class="visually-hidden" id="forwarding-external-message">
  Opens external website.
</span>

    <span class="visually-hidden" id="checkout-context-step-one">
  Customer information - Best Watches Store - Checkout
</span>




</div>