<div class="main__content">

    <div class="step" data-step="payment_method">
        <div class="step__sections">
            <form method="post" action="/hoan-thanh">
                <input type="hidden" name="checkout[invoice]" value="<?= $id ?>">
                <div class="section section--billing-address" data-billing-address="">
                    <div class="section__header">
                        <h2 class="section__title">Phương thức thanh toán</h2>
                        <p class="section__text">
                            Tất cả giao dịch được bảo mật và mã hóa.
                        </p>
                    </div>

                    <div class="section__content">
                        <fieldset class="content-box">
                            <div class="radio-wrapper content-box__row" data-same-billing-address="">
                                <div class="radio__input">
                                    <input class="input-radio" type="radio" value="1" checked="checked" name="checkout[different_billing_address]" id="checkout_different_billing_address_false">
                                </div>

                                <label class="radio__label content-box__emphasis" for="checkout_different_billing_address_false">
                                    Thanh toán khi giao hàng
                                </label>
                            </div>

                            <div class="radio-wrapper content-box__row" data-different-billing-address="">
                                <div class="radio__input">
                                    <input class="input-radio"  aria-expanded="false" type="radio" value="2" name="checkout[different_billing_address]" id="checkout_different_billing_address_true">
                                </div>
                                <label class="radio__label content-box__emphasis" for="checkout_different_billing_address_true">
                                    Thanh toán online nội địa
                                </label>
                            </div>

                            <div class="radio-group__row content-box__row content-box__row--secondary hidden" id="section--billing-address__different">
                                <div class="fieldset" data-address-fields="">
                                    <div>

                                        <button data-price="<?= $price ?>" data-phone="<?= $phone ?>" data-id="<?= $id ?>"  name="button" type="button" id="paymentOnepay">
                                            <img src="/public/img/icons/onepay.png">
                                         </button>
                                    </div>

                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>




                <div class="step__footer" data-step-footer="">
                    <input type="hidden" name="checkout[total_price]" id="checkout_total_price" value="37293">
                    <input type="hidden" name="complete" value="1">

                    <div class="shown-if-js">
                        <button name="button" type="submit" class="step__footer__continue-btn btn " aria-busy="false">
                              <span class="btn__content">
                                Hoàn thành
                              </span>
                            <svg class="icon-svg icon-svg--size-18 btn__spinner icon-svg--spinner-button" aria-hidden="true" focusable="false"> <use xlink:href="#spinner-button"></use> </svg>
                        </button>
                    </div>
                    <a class="step__footer__previous-link" href="/checkouts/customerinfo"><svg focusable="false" aria-hidden="true" class="icon-svg icon-svg--color-accent icon-svg--size-10 previous-link__icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><path d="M8 1L7 0 3 4 2 5l1 1 4 4 1-1-4-4"></path></svg><span class="step__footer__previous-link-content">Trở lại</span></a>
                </div>


             </form>
        </div>

    </div>


    <span class="visually-hidden" id="forwarding-external-new-window-message">
  Opens external website in a new window.
</span>

    <span class="visually-hidden" id="forwarding-new-window-message">
  Opens in a new window.
</span>

    <span class="visually-hidden" id="forwarding-external-message">
  Opens external website.
</span>

    <span class="visually-hidden" id="checkout-context-step-one">
  Customer information - Best Watches Store - Checkout
</span>

</div>