<?php foreach ($bestSellers as $product): ?>
<div class="item">

    <div class="product-image">

        <a class="thumb" href="/san-pham/chi-tiet-san-pham/<?= $product->id ?>">
            <img src="/public/uploads/product/<?= $product->image ?>" alt="<?= $product->product_name ?>" />
        </a>
    </div>

    <div class="product-info">

        <h3 class="product-name"><a href= "/san-pham/chi-tiet-san-pham/<?= $product->id ?>"><?= $product->product_name ?></a></h3>


        <span class="price">

        <span class='money'><?= number_format($product->sale_price ,0  , 0 , '.')?> VND</span>

      </span>

    </div>

</div>
<?php endforeach; ?>