<?php foreach ($bestSellers as $product): ?>
<div class="item">

    <div class="product-image">

        <a class="thumb" href="/san-pham/chi-tiet-san-pham/<?= $product->id ?>">
            <?php if($product->discount){ ?>
                <span class="sale-tag"></span>
            <?php } ?>
            <img src="/public/uploads/product/<?= $product->image ?>" alt="<?= $product->product_name ?>" />
        </a>
    </div>

    <div class="product-info">

        <h3 class="product-name"><a href= "/san-pham/chi-tiet-san-pham/<?= $product->id ?>"><?= $product->product_name ?></a></h3>


        <span class="price">

            <?php if($product->discount){ ?>
                <span class='money'><?= number_format((int)$product->sale_price - ((int)$product->discount/100 * (int)$product->sale_price) ,0  , 0 , '.')?> VND</span>
            <?php }else{ ?>
                <span class='money'><?= number_format($product->sale_price ,0  , 0 , '.')?> VND</span>
            <?php } ?>



      </span>

    </div>

</div>
<?php endforeach; ?>