<?php
namespace App\Models;
/**
 * PurchaseInvoicesDetail
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-01-10, 00:54:16
 */
class PurchaseInvoicesDetail extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    protected $purchase_invoices_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    protected $product_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=50, nullable=true)
     */
    protected $quantity;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    protected $price;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    protected $name_seller;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    protected $created_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field purchase_invoices_id
     *
     * @param integer $purchase_invoices_id
     * @return $this
     */
    public function setPurchaseInvoicesId($purchase_invoices_id)
    {
        $this->purchase_invoices_id = $purchase_invoices_id;

        return $this;
    }

    /**
     * Method to set the value of field product_id
     *
     * @param integer $product_id
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->product_id = $product_id;

        return $this;
    }

    /**
     * Method to set the value of field quantity
     *
     * @param integer $quantity
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Method to set the value of field price
     *
     * @param string $price
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Method to set the value of field name_seller
     *
     * @param string $name_seller
     * @return $this
     */
    public function setNameSeller($name_seller)
    {
        $this->name_seller = $name_seller;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field purchase_invoices_id
     *
     * @return integer
     */
    public function getPurchaseInvoicesId()
    {
        return $this->purchase_invoices_id;
    }

    /**
     * Returns the value of field product_id
     *
     * @return integer
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Returns the value of field quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Returns the value of field price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Returns the value of field name_seller
     *
     * @return string
     */
    public function getNameSeller()
    {
        return $this->name_seller;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("b4_22077174_huuquynh");
        $this->setSource("purchase_invoices_detail");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'purchase_invoices_detail';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return PurchaseInvoicesDetail[]|PurchaseInvoicesDetail|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return PurchaseInvoicesDetail|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'purchase_invoices_id' => 'purchase_invoices_id',
            'product_id' => 'product_id',
            'quantity' => 'quantity',
            'price' => 'price',
            'name_seller' => 'name_seller',
            'created_at' => 'created_at'
        ];
    }

}
