<div class="custom-banner box" xmlns="http://www.w3.org/1999/html">
    <div class="ctb ctb-top light-shadow wow fadeInUp animated" data-wow-delay="0.15s">
        <div class="row equal">
            <div class="large-6 small-12 columns">
                <div class="ctb-img wow bounceInDown animated" data-wow-delay="0.15s">
                    <img src="/public/img/ctb-1e0a9.png?4621688722820174607" alt="" />
                </div>
            </div>
            <div class="text-ctb-1 large-6 small-12 columns">
                <div class="d-table">
                    <div class="ctb-des d-table-cell">
                        <h3>Đồng hồ chính xác  <br/>nhất thế giới</h3>
                        <p> Chất liệu tốt nhât . Tỉ mỉ đến từng chi tiết sản xuất . Với đội ngũ chuyên gia tốt nhất . Mang đến sự sang trọng nhưng không kém phần chất lượng. </p>
                        <a class="ct-btn" href="/public/files/16416517-first-post.html" title="">Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ctb ctb-bot wow fadeInUp animated" data-wow-delay="0.15s">
        <div class="row">
            <div class="large-6 small-12 columns">
                <div class="ctb-des">
                    <h3>Thiết kế sáng tạo <br/> phong cách hơn</h3>
                    <p>Với đội ngũ chuyên gia thiết kế chuyên nghiệp <br/> Mang đến nhiều cảm hứng thiết kế phong cách <br/>sang trọng hơn lôi cuốn đến từng chi tiết trên sản phẩm .</p>
                    <a class="ct-btn" href="/public/files/16416517-first-post.html" title="">Xem thêm</a>
                </div>
            </div>

        </div>
    </div>
</div>
