<div class="featured-collection box wow fadeInUp animated" data-wow-delay="0.15s">
    <div class="row">
        <div class="row">
            <div class="small-12 medium-12 large-12 columns">
                <div class="box-title">
                    <h3>Bộ sưu tâp</h3>
                    <span class="abs"><i class="fa fa-th-list"></i></span>
                </div>
                <div class="box-content wow fadeInUp animated" data-wow-delay="0.15s">
                    <div id="categories-scroll" class="row">





                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon1e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/frontpage.html" title="Browse our for men collection">
                                    <span class="featured-box-title">Nam</span>
                                    <span class="featured-box-count">17 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon2e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/women.html" title="Browse our for women collection">
                                    <span class="featured-box-title">Nữ</span>
                                    <span class="featured-box-count">9 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon3e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/luggage-travel-gear.html" title="Browse our sport collection">
                                    <span class="featured-box-title">Thể thao</span>
                                    <span class="featured-box-count">8 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon4e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/luggage-travel-gear.html" title="Browse our luxury collection">
                                    <span class="featured-box-title">Sang trọng</span>
                                    <span class="featured-box-count">8 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon5e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/baby.html" title="Browse our basketball collection">
                                    <span class="featured-box-title">Bóng rổ</span>
                                    <span class="featured-box-count">10 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon6e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/boys.html" title="Browse our Training collection">
                                    <span class="featured-box-title">Đào tạo</span>
                                    <span class="featured-box-count">17 items</span>
                                </a>
                            </div>
                        </div>



                        <div class="item">

                            <div class="featured-box">
                                <img src="/public/img/icon7e0a9.png?4621688722820174607" alt="Best Watches Store" />
                                <a href="collections/frontpage.html" title="Browse our football collection">
                                    <span class="featured-box-title">Bóng đá</span>
                                    <span class="featured-box-count">17 items</span>
                                </a>
                            </div>
                        </div>




                    </div>
                </div>

            </div>
        </div>
    </div>
</div>