
<nav class="tab-bar show-for-small">
    <section class="row text-center topbar-mobile">
        <div class="small-4 columns ">
            <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
        </div>
        <div class="small-4 columns ">
            <button data-dropdown="use" aria-controls="use" aria-expanded="false" class="no-btn"><i class="fa fa-user"></i></button>

            <ul id="use" class="f-dropdown mobile-links" data-dropdown-content aria-hidden="true" tabindex="-1">

                <li>
                    <a href="account/login.html" id="customer_login_link">Login</a>
                </li>
                <li>
                    <a href="account/register.html" id="customer_register_link">Register</a>
                </li>

            </ul>

        </div>
        <div class="small-4 columns ">
            <a class="right-off-canvas-toggle menu-icon" href="#"><i class="fa fa-shopping-cart"></i></a>
        </div>
    </section>
</nav>
<aside class="left-off-canvas-menu">
    <!--Top Menu -->

    <!-- This is where the main menu links render-->
    <ul class="mobile-menu">






        <li class="nav-item first active">
            <a href="index.html" title="">Home</a>

        </li>






        <li class="nav-item has-dropdown">
            <a href="collections/all.html" title="">Catalog</a>

            <ul class="dropdown">


                <li class=" first">
                    <a class="first" href="collections/men.html">Men</a>
                </li>

                <li class="">
                    <a class="" href="collections/women.html">Women</a>
                </li>

                <li class="">
                    <a class="" href="collections/luggage-travel-gear.html">Luggage & Travel Gear</a>
                </li>

                <li class="">
                    <a class="" href="collections/girls.html">Girls</a>
                </li>

                <li class="">
                    <a class="" href="collections/boys.html">Boys</a>
                </li>

                <li class="">
                    <a class="" href="collections/baby.html">Baby</a>
                </li>

                <li class=" last">
                    <a class="last" href="collections/frontpage.html">Novelty, Costumes & More</a>
                </li>


            </ul>

        </li>






        <li class="nav-item">
            <a href="blogs/news.html" title="">Blog</a>

        </li>






        <li class="nav-item">
            <a href="pages/wish-list.html" title="">Wishlist</a>

        </li>






        <li class="nav-item last">
            <a href="pages/about-us.html" title="">About Us</a>

        </li>

    </ul>

    <!-- End Menu -->
</aside>
<aside class="right-off-canvas-menu">
    <div class="topcart">

        <div>
            <p class="empty">Your cart is currently empty!</p>
        </div>

    </div>
</aside>