<main role="main">

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="/trang-chu" class="homepage-link" title="Back to the frontpage">Trang chủ</a>
                </li>

                <li class="current">
                    <a href="#"><?= $this->session->get('product') ?></a>
                </li>
            </ul>
        </div>
    </div>
    <!-- End Breadcrumbs -->




    <div class="row">
        <div class="small-12 medium-4 large-3 columns sidebar wow fadeInUp animated" data-wow-delay="0.15s">
            <div id="collectionFilters" class="collection-filters" >





                <div class="grid-uniform">
                    <div class="grid-item small--one-half medium--one-third">
                        <h3><span>Thể loại</span></h3>
                        <ul class="categories-filters">
                            <li><a href="/san-pham/tat-ca-san-pham" >Tất cả</a></li>
                            <?php foreach ($producttype as $item): ?>
                                <li><a href="/san-pham/<?= $item->redirect ?>" ><?= $item->name ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>


                <div class="grid-uniform">


                    <div class="grid-item small--one-half medium--one-third">
                        <h3>Thương hiệu</h3>
                        <ul class="advanced-filters">
                            <li id="producer" data-currenttype="<?= $currentType ?>" data-id="0" class="advanced-filter" data-group="Brand"><a href="#" title="">Tất cả</a></li>
                            <?php foreach ($producer as $item): ?>
                                <li id="producer" data-currenttype="<?= $currentType ?>" data-id="<?= preg_replace('/[_\\W]+/' ,"_" ,$item->trademark)?>" class="advanced-filter" data-group="Brand"><a href="#" title=""><?= $item->trademark ?></a></li>
                            <?php endforeach; ?>

<!--                            <li class="advanced-filter active-filter" data-group="Brand"><a href="all/brand_cuckoo.html" title="Narrow selection to products matching tag Brand_Cuckoo">CASIO</a></li>-->



                        </ul>
                    </div>



                    <div class="grid-item small--one-half medium--one-third">
                        <h3>Khoảng giá</h3>
                        <ul class="advanced-filters">

                            <li class="advanced-filter" data-currenttype="<?= $currentType ?>" data-id="0_to_5000000" data-group="Price"><a href="#">Dưới 5.000.000</a></li>

                            <li class="advanced-filter" data-currenttype="<?= $currentType ?>" data-id="5000000_to_10000000" data-group="Price"><a href="#" >Từ 5.000.000 đến 10.000.000</a></li>

                            <li class="advanced-filter" data-currenttype="<?= $currentType ?>" data-id="10000000_to_20000000" data-group="Price"><a href="#">Từ 10.000.000 đến 20.000.000</a></li>

                            <li class="advanced-filter" data-currenttype="<?= $currentType ?>" data-id="20000000_etc" data-group="Price"><a href="#">Trên 20.000.000</a></li>

                        </ul>
                    </div>


                </div>

            </div>





            <div class="latest-products mini-products-list">
                <div class="box-title">
                    <h3>Đồng hồ bán chạy nhất</h3>
                </div>
                <div class="box-content">
                    <div  id="sidebar-list">
                        <?php $this->partial('product/bestsellers') ?>
                    </div>
                </div>
            </div>

        </div>
        <div class="small-12 medium-8 large-9 columns col-main">
            <div class="collection-info">
<!--                <h1 class="page-title collection-title">Tất cả sản phẩm</h1>-->
                <img src="/public/img/215982cfe340e5c.jpg" alt="Products" />
            </div>
            <div class="collection-products">
                <div class="toolbar">
                    <div class="sort-by">
                        <label for="sortBy">Sắp xếp theo</label>
                        <select data-currenttype="<?= $currentType ?>" name="sortBy" id="sortBy">
                            <option value="manual">Sản phẩm nổi bật</option>
                            <option value="best-selling">Sản phầm bán chạy nhất</option>
                            <option value="title-ascending">Sắp xếp theo  từ A-Z</option>
                            <option value="title-descending">Sắp xếp theo Z-A</option>
                            <option value="price-ascending">Giá từ thấp đến cao</option>
                            <option value="price-descending">Giá từ cao đến thấp</option>
                            <option value="created-descending">Từ mới đến cũ</option>
                            <option value="created-ascending">Từ cũ đến mới</option>
                        </select>
                    </div>

                    <div class="collection-view">
                        <label>View</label>

                        <strong class="view-grid" title="Grid view" data-view="grid">Hiển thị theo ô</strong>

                    </div>


                </div>
                <div id="container_product">
                    <?php echo $this->getContent(); ?>
                </div>


            </div>
        </div>



</main>
