<section id="slider" class="">
    <div class="slideshow box">
        <!-- Desktop Slider -->
        <div class="slideshow-wrapper wow">
            <div class="preloader"></div>
            <ul data-orbit data-options="bullets:false;pause_on_hover:true;resume_on_mouseout:true;" class="text-center">
                <li>
                    <img src="/public/img/slideshow_image_1e0a9.png?4621688722820174607" alt="Best Watches Store" />
                    <div class="orbit-caption">
                        <h2>Đồng hồ lấy cảm hứng từ quân đội</h2>
                        <p>Cảm giác lướt sóng và trượt ván với bộ đồng hồ sẵn sàng cho hành động <br> giống như của Rip Curl và hơn thế nữa</p>
                        <a class="button" href="products/samsung-galaxy-s5-black-16gb-sprint.html">Tìm hiểu thêm</a>
                    </div>
                </li>

                <li>
                    <img src="/public/img/slideshow_image_2e0a9.png?4621688722820174607" alt="Best Watches Store" />
                    <div class="orbit-caption">
                        <h2>Đồng hồ Sturhling Tourbillon</h2>
                        <p>Sturhling Tourbillon biểu tượng cho độ chính xác tuyệt vời của cỗ máy đo thời gian <br> Sturhling Tourbillon là thương hiệu của những mẫu đồng hồ đẳng cấp,phong cách và sành điệu trong vài thập kỷ qua …</p>
                        <a class="button" href="collections/baby/products/nine-west-womens-nostalgia-leather-boot.html">Tìm hiểu thêm</a>
                    </div>
                </li>


            </ul>
        </div>
    </div>
    <!-- End Desktop Slider -->
</section>