<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row-fluid" style="margin-left: 10%">
    <div class="span9">
        <div class="widget-title">
            <h3 style="text-align: center;">Thông tin chi tiết</h3>
        </div>
        <div class="widget-box">

            <div class="widget-content nopadding">
                <?php
                echo $this->tag->form(
                    [
                        "backend/sales_invoice_detail/save",
                        "autocomplete" => "off",
                        "class" => "form-horizontal",
                        "id" => 'invoice_detail_edit',
                        "enctype" => "multipart/form-data"
                    ]
                );
                ?>
                <div id="form-wizard-1" class="step">

                    <div class="control-group">
                        <label class="control-label">Id :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["id" , 'readonly' => 'true' , "size" => 30, "class" => "form-control"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Product :</label>
                        <div class="controls">
                            <select name="product_id" id="product_id" style="border-radius: 4px">
                                <?php foreach ($product as $products): ?>
                                    <?php if ($products->id == $product_id){ ?>
                                        <option value="<?php echo $products->id ?>" selected><?php echo $products->product_name ?></option>
                                    <?php }else{ ?>
                                        <option value="<?php echo $products->id ?>"><?php echo $products->product_name ?></option>
                                    <?php } ?>
                                <?php endforeach; ?>
                            </select>
                           </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" style="margin-top: -5px">Quatity :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Comment :</label>
                        <div class="controls">
                            <?php echo $this->tag->textField(["comment", "size" => 30, "class" => "form-control", "id" => "fieldComment"]) ?>
                        </div>
                    </div>


                </div>
                <?php echo $this->tag->endForm(); ?>
                <div class="control-group" style="margin-top: 6% ; margin-right: 2%">
                    <label class="control-label"></label>
                    <div class="controls" style="float: right; margin-top: -5%;">
                        <button form="invoice_detail_edit" class="btn btn-success icon-ok"><span class="glyphicon glyphicon-remove-circle"></span> Save and List</button>
                        <?php echo $this->tag->linkTo(["backend/sales_invoice_detail/index/".$invoice_id, '<button class="btn btn-info icon-list "><span class="glyphicon glyphicon-remove-circle"></span> List</button>']); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
