<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="panel-body">

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Product</th>
                <th style="background-color: #0288d1;color: #ffffff;">Quantity</th>
                <th style="background-color: #0288d1;color: #ffffff;">Discount</th>
                <th style="background-color: #0288d1;color: #ffffff;">Price</th>
                <th style="background-color: #0288d1;color: #ffffff;">Total</th>
                <th style="background-color: #0288d1;color: #ffffff;">Comment</th>

            </tr>
            <?php foreach ($page->items as $sales_invoice_detail): ?>
                <tr>

                    <td><?php echo $this->tag->linkTo(["backend/sales_invoice_detail/edit/" . $sales_invoice_detail->id, $sales_invoice_detail->id ]); ?></td>
                    <td><?php echo $sales_invoice_detail->product_id ?></td>
                    <td><?php echo $sales_invoice_detail->quantity ?></td>
                    <td><?php echo $sales_invoice_detail->discount ?></td>
                    <td><?php echo number_format($sales_invoice_detail->price ,0  , 0 , '.')  ?></td>
                    <td><?php echo number_format($sales_invoice_detail->total ,0  , 0 , '.')  ?></td>
                    <td><?php echo $sales_invoice_detail->comment ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
