<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search sales_invoice_detail
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["sales_invoice_detail/new", "Create sales_invoice_detail"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "sales_invoice_detail/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSalesInvoiceId" class="col-sm-2 control-label">Sales Of Invoice</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sales_invoice_id", "type" => "number", "class" => "form-control", "id" => "fieldSalesInvoiceId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProductId" class="col-sm-2 control-label">Product</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_id", "type" => "number", "class" => "form-control", "id" => "fieldProductId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantity" class="col-sm-2 control-label">Quantity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["quantity", "type" => "number", "class" => "form-control", "id" => "fieldQuantity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDiscount" class="col-sm-2 control-label">Discount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["discount", "size" => 30, "class" => "form-control", "id" => "fieldDiscount"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTotal" class="col-sm-2 control-label">Total</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["total", "size" => 30, "class" => "form-control", "id" => "fieldTotal"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldComment" class="col-sm-2 control-label">Comment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["comment", "size" => 30, "class" => "form-control", "id" => "fieldComment"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>



<div class="panel-body">

    <div class="clearfix"></div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
            <tbody><tr >
                <th style="background-color: #0288d1;color: #ffffff;">Id</th>
                <th style="background-color: #0288d1;color: #ffffff;">Product</th>
                <th style="background-color: #0288d1;color: #ffffff;">Quantity</th>
                <th style="background-color: #0288d1;color: #ffffff;">Discount</th>
                <th style="background-color: #0288d1;color: #ffffff;">Price</th>
                <th style="background-color: #0288d1;color: #ffffff;">Total</th>
                <th style="background-color: #0288d1;color: #ffffff;">Comment</th>

            </tr>
            <?php foreach ($page->items as $sales_invoice_detail): ?>
                <tr>

                    <td><?php echo $this->tag->linkTo(["backend/sales_invoice_detail/edit/" . $sales_invoice_detail->id, $sales_invoice_detail->id ]); ?></td>
                    <td><?php echo $sales_invoice_detail->product_id ?></td>
                    <td><?php echo $sales_invoice_detail->quantity ?></td>
                    <td><?php echo $sales_invoice_detail->discount ?></td>
                    <td><?php echo number_format($sales_invoice_detail->price ,0  , 0 , '.')  ?></td>
                    <td><?php echo number_format($sales_invoice_detail->total ,0  , 0 , '.')  ?></td>
                    <td><?php echo $sales_invoice_detail->comment ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody></table>
    </div>
    <div class="col-lg-12 center">

        <div style="overflow: hidden" class="paginationsa">
            <ul style="float: right">
                <?php echo \App\Library\Unit::showPagination($page->total_pages ,
                    $page->current ,
                    $page->before ,
                    $page->next ,
                    $page->last
                ) ?>
            </ul>
        </div>
    </div>
</div>
