<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["sales_invoice_detail/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["sales_invoice_detail/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Sales Of Invoice</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Discount</th>
            <th>Price</th>
            <th>Total</th>
            <th>Comment</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $sales_invoice_detail): ?>
            <tr>
                <td><?php echo $sales_invoice_detail->id ?></td>
            <td><?php echo $sales_invoice_detail->sales_invoice_id ?></td>
            <td><?php echo $sales_invoice_detail->product_id ?></td>
            <td><?php echo $sales_invoice_detail->quantity ?></td>
            <td><?php echo $sales_invoice_detail->discount ?></td>
            <td><?php echo $sales_invoice_detail->price ?></td>
            <td><?php echo $sales_invoice_detail->total ?></td>
            <td><?php echo $sales_invoice_detail->comment ?></td>

                <td><?php echo $this->tag->linkTo(["sales_invoice_detail/edit/" . $sales_invoice_detail->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["sales_invoice_detail/delete/" . $sales_invoice_detail->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("sales_invoice_detail/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice_detail/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice_detail/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("sales_invoice_detail/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
